<?php
use Magento\Framework\Pricing\Helper\Data as PricingHelper;

/** @var \Fiserv\Payments\Block\CommerceHub\AdminHtml\Declines\Order $block */
$order = $block->getFailedOrder();
$transactions = $block->getFailedTransactionsForOrder();
$giftAmount = $block->getAppliedGiftCardAmount();
$isSuccessful = isset($order[$block::KEY_SUCCESSFUL]) && $order[$block::KEY_SUCCESSFUL] === true;
$orderTotal = htmlspecialchars(isset($order["grandTotal"]) ? $order["grandTotal"] : "N/A", ENT_QUOTES, 'UTF-8');
?>

<div class="admin__data-grid-wrap">
    <!-- Black Banner -->
    <div class="black-banner">
        <div class="banner-left">
            <button class="back-button"><a href="<?php echo $block->getUrl('fiserv/declines/preview'); ?>"><?php echo __('<'); ?></a></button>
            <span class="order-id"><?php echo __('Order ID: '); ?><?= htmlspecialchars(isset($order["order_increment_id"]) ? $order["order_increment_id"] : "N/A", ENT_QUOTES, 'UTF-8'); ?></span>
        </div>
        <div class="banner-right">
            <span class="order-state"><?php echo __('Order State: '); ?><?= htmlspecialchars(isset($order["order_state"]) ? strtoupper($order["order_state"]) : "N/A", ENT_QUOTES, 'UTF-8'); ?></span>
        </div>
    </div>

    <!-- Set up a container to manage layout -->
    <div class="main-content-container">
        <div id="failed-order-container">
            <div class="three-col">
                <!-- Items Ordered Section -->
                <div class="failed-transaction-section header-margin">
                    <div class="failed-transaction-section-header"><?php echo __('Items Ordered'); ?></div>
                    <div class="failed-transaction-section-body">
                        <div class="failed-transaction-detail-header">
                            <div class="failed-transaction-detail-column"><?php echo __('Product'); ?></div>
                            <div class="failed-transaction-detail-column"><?php echo __('Quantity'); ?></div>
                            <div class="failed-transaction-detail-column"><?php echo __('Price'); ?></div>
                            <div class="failed-transaction-detail-column"><?php echo __('Subtotal'); ?></div>
                        </div>
                        <div class="failed-transaction-line"></div>
						<?php foreach (isset($order["items"]) ? json_decode($order["items"], true) : [] as $item): ?>
                            <div class="failed-transaction-detail-row">
                                <div class="failed-transaction-detail-column"><?= htmlspecialchars(isset($item["name"]) ? $item["name"] : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                                <div class="failed-transaction-detail-column"><?= htmlspecialchars(isset($item["qty"]) ? $item["qty"] : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                                <div class="failed-transaction-detail-column"><?= htmlspecialchars(isset($item["price"]) ? $block->formatPrice($item["price"]) : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                                <div class="failed-transaction-detail-column"><?= htmlspecialchars(isset($item["price"]) && isset($item["qty"]) ? $block->formatPrice($item["qty"] * $item["price"]) : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                            </div>
						<?php endforeach; ?>
                    </div>
                </div>

                <!-- Order and Account Details Section -->
                <div class="failed-transaction-section">
                    <div class="failed-transaction-section-header"><?php echo __('Order and Account Details'); ?></div>
                    <div class="failed-transaction-section-body">
                        <div class="order-account-top">
                            <div class="failed-transaction-detail-row">
                                <div class="failed-transaction-detail-column">
                                    <div class="failed-transaction-detail-label"><?php echo __('Order Date (UTC)'); ?></div>
                                    <div class="failed-transaction-detail-value"><?= htmlspecialchars(isset($order["date_time"]) ? $order["date_time"] : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                                </div>
                                <div class="failed-transaction-detail-column">
                                    <div class="failed-transaction-detail-label"><?php echo __('Order State'); ?></div>
                                    <div class="failed-transaction-detail-value"><?= htmlspecialchars(isset($order["order_state"]) ? $order["order_state"] : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                                </div>
                            </div>
                            <div class="failed-transaction-detail-row">
                                <div class="failed-transaction-detail-column">
                                    <div class="failed-transaction-detail-label"><?php echo __('Shipping Address'); ?></div>
                                    <div class="failed-transaction-detail-value"><?= htmlspecialchars(isset($order["shipping_address"]) && !empty($order["shipping_address"]) ? $order["shipping_address"] : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                                </div>
                                <div class="failed-transaction-detail-column">
                                    <div class="failed-transaction-detail-label"><?php echo __('Billing Address'); ?></div>
                                    <div class="failed-transaction-detail-value"><?= htmlspecialchars(isset($order["billing_address"]) ? $order["billing_address"] : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                                </div>
                            </div>
                        </div>
                        <div class="order-account-line"></div>
                        <div class="order-account-bottom">
                            <div class="failed-transaction-detail-row">
                                <div class="failed-transaction-detail-column">
                                    <div class="failed-transaction-detail-label"><?php echo __('Customer Name'); ?></div>
                                    <div class="failed-transaction-detail-value"><?= htmlspecialchars(isset($order["customer_name"]) ? $order["customer_name"] : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                                </div>
                                <div class="failed-transaction-detail-column">
                                    <div class="failed-transaction-detail-label"><?php echo __('Email'); ?></div>
                                    <div class="failed-transaction-detail-value"><?= htmlspecialchars(isset($order["customer_email"]) ? $order["customer_email"] : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="two-col">
                <!-- Order Totals Section -->
                <div class="failed-order-section full-height header-margin">
                    <div class="failed-transaction-section-header"><?php echo __('Order Totals'); ?></div>
                    <div class="failed-transaction-section-body">
                        <div class="failed-transaction-detail">
                            <div class="failed-transaction-detail-label"><?php echo __('Subtotal'); ?></div>
                            <div class="failed-transaction-detail-value"><?= htmlspecialchars(isset($order["subtotal"]) ? $block->formatPrice($order["subtotal"]) : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                        </div>
						<?php if ($giftAmount > 0.00): ?>
                            <div class="failed-transaction-detail">
                                <div class="failed-transaction-detail-label"><?php echo __('Gift Cards'); ?></div>
                                <div class="failed-transaction-detail-value">-<?= htmlspecialchars($block->formatPrice($giftAmount), ENT_QUOTES, 'UTF-8'); ?></div>
                            </div>
						<?php endif; ?>
                        <div class="failed-transaction-detail">
                            <div class="failed-transaction-detail-label"><?php echo __('Shipping & Handling'); ?></div>
                            <div class="failed-transaction-detail-value"><?= htmlspecialchars(isset($order["shipping_handling"]) ? $block->formatPrice($order["shipping_handling"]) : "N/A", ENT_QUOTES, 'UTF-8'); ?></div>
                        </div>
                        <div class="failed-transaction-line"></div>
                        <div class="failed-transaction-detail">
                            <div class="failed-transaction-detail-label"><?php echo __('Order Total'); ?></div>
                            <div class="failed-transaction-detail-value"><?= $orderTotal; ?></div>
                        </div>

                        <!-- Order Notes Section -->
                        <div class="order-notes-section">
                            <div class="order-notes-header"><?php echo __('Order Notes'); ?></div>
                            <div class="order-notes-box">
                                <div class="order-notes-list">
									<?php echo htmlspecialchars(isset($order['notes']) && !is_null($order['notes']) ? $order['notes'] : "", ENT_QUOTES, 'UTF-8'); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
	<div class="search-pagination-container">
		<input type="text" id="searchInput" placeholder="Search for keywords">
		<div class="paginationContainerTop">
			<label for="rowsPerPage">Limit:</label>
			<select id="rowsPerPage">
				<option value="5">5</option>
				<option value="10">10</option>
				<option value="15">15</option>
				<option value="20" selected>20</option>
			</select>
			<span id="paginationInfoTop" class="pagination-info"></span>
		</div>
	</div>

    <table id="transactionsTable" class="data-table">
        <thead>
        <tr>
            <th>Date/Time</th>
            <th>Transaction ID</th>
            <th>Transaction State</th>
            <th>Approval Status</th>
            <th>Total Amount</th>
	    <th>IP Address</th>
            <th>Payment Action</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody id="tableBody">
		<?php foreach ($transactions as $transaction): ?>
            <tr>
                <td><?php echo htmlspecialchars(isset($transaction['date_time']) ? $transaction['date_time'] : "N/A", ENT_QUOTES, 'UTF-8'); ?></td>
				<td>
					<?php echo htmlspecialchars(isset($transaction['transaction_id']) ? $transaction['transaction_id'] : "N/A", ENT_QUOTES, 'UTF-8'); ?>
				</td>
                <td><?php echo htmlspecialchars(isset($transaction["transaction_state"]) ? strtoupper($transaction["transaction_state"]) : "N/A", ENT_QUOTES, 'UTF-8'); ?></td>
                <td><?php echo htmlspecialchars(isset($transaction["approval_status"]) ? ucfirst($transaction["approval_status"]) : "N/A", ENT_QUOTES, 'UTF-8'); ?></td>
				<td><?php echo htmlspecialchars($block->formatPrice($orderTotal), ENT_QUOTES, 'UTF-8'); ?></td>
				<td><?php echo htmlspecialchars(isset($transaction['remote_ip']) ? $transaction['remote_ip'] : "N/A", ENT_QUOTES, 'UTF-8'); ?></td>
				<td><?php echo htmlspecialchars(isset($transaction['paymentAction']) ? $transaction['paymentAction'] : "N/A", ENT_QUOTES, 'UTF-8'); ?></td>
                <td>
					<?php if(isset($transaction[$block::KEY_SUCCESSFUL]) && $transaction[$block::KEY_SUCCESSFUL] === true): ?>
                        <a href="<?php echo $block->getUrl('sales/transactions/view', ['txn_id' => $transaction[$block::KEY_SUCCESSFUL_TXN]]); ?>">View</a>
					<?php elseif($transaction['transaction_id'] !== "N/A"): ?>
                        <a href="<?php echo $block->getUrl('fiserv/declines/transaction', ['transaction_id' => $transaction['transaction_id']]); ?>">View</a>
					<?php endif ?>
                </td>
            </tr>
		<?php endforeach; ?>
        </tbody>
    </table>
	<div id="paginationControls"></div>
</div>

<script type="text/x-magento-init">
{
	"*": {
		"Magento_Ui/js/core/app": {
			"components": {
				"failed-transaction": {
					"component": "Fiserv_Payments/js/view/declines/failed-transaction"
				}
			}
		}
	}
}
</script>

