<?php
/**
 * @var \Fiserv\Payments\Block\Adminhtml\Declines\Preview $block
 */
$orders = $block->getOrdersWithDeclines();
?>

<?php if($orders) : ?>

	<div class="search-pagination-container">
		<input type="text" id="searchInput" placeholder="Search for keywords">
		<div class="paginationContainerTop">
			<label for="rowsPerPage">Limit:</label>
			<select id="rowsPerPage">
				<option value="5">5</option>
				<option value="10">10</option>
				<option value="15">15</option>
				<option value="20" selected>20</option>
			</select>
			<span id="paginationInfoTop" class="pagination-info"></span>
		</div>
	</div>

	<table id="transactionsTable" class="data-table">
		<thead>
			<tr>
				<th>Date/Time</th>
				<th>Order ID</th>
				<th>Customer Name</th>
				<th>Order State</th>
				<th>Order Amount</th>
				<th>IP Address</th>
				<th>Action</th>
			</tr>
		<thead>
		<tbody id="tableBody">
			<?php foreach ($orders as $order): ?>
				<tr>
					<td><?php echo isset($order['date_time']) ? $order['date_time'] : "N/A"; ?></td>
					<td><?php echo isset($order['order_increment_id']) ? $order['order_increment_id'] : "N/A"; ?></td>
					<td><?php echo isset($order['customer_name']) ? $order['customer_name'] : "N/A"; ?></td>
					<td><?php echo isset($order['order_state']) ? strtoupper($order['order_state']) : "N/A"; ?></td>
					<td><?php echo isset($order['grandTotal']) ? $block->formatPrice($order['grandTotal']) : "N/A"; ?></td>
					<td><?php echo isset($order['failed_transaction_data']['remote_ip']) ? $order['failed_transaction_data']['remote_ip'] : "N/A"; ?></td>
					<td>
						<a href="<?php echo $block->getUrl('fiserv/declines/order', ['id' => $order['order_increment_id']]); ?>">View</a>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<div id="noRecordsMessage" style="display: none;margin-bottom: 20%;">No failed orders found!</div>

	<div id="paginationControls"></div>
<?php else: ?>
	<div style="margin-bottom: 20%">No failed orders found!</div>
<?php endif; ?>

<script type="text/x-magento-init">
{
	"*": {
		"Magento_Ui/js/core/app": {
			"components": {
				"failed-transaction": {
					"component": "Fiserv_Payments/js/view/declines/failed-transaction"
				}
			}
		}
	}
}
</script>

