<?php

/**
 * @var \Fiserv\Payments\Block\Adminhtml\Declines\Preview $block
 */
$orders = $block->getOrders();
$totalPages = $block->getTotalPages();
$allApprovalStatus = $block->getAllApprovalStatus();
$allOrderState = $block->getAllOrderState();
?>

<?php if ($orders) : ?>
    <div class="search-pagination-container">
        <div class="filter-wrapper">
            <div class="filter-item">
                <input type="text" id="searchInput" placeholder="Search for keywords">
            </div>
            <div class="actionContainer">
                <button id="toggleFilterBtn" style="margin-left: 20px;">Filter</button>

                <!-- Export Button Implementation Start -->
                <label for="exportOptions"></label>
                <span style="display: flex;position: relative;">
                    <button id="exportDropdownButton" class="exportButton" style="background-color: transparent; border: none;">
                    <img style="width: 14px; height: 14px;" src="<?php echo htmlspecialchars($this->getViewFileUrl('Fiserv_Payments::images/Export_Button.svg'), ENT_QUOTES, 'UTF-8'); ?>" alt="Export">
                    Export
                    <span id="exportArrow" class="arrow-down">▼</span><span id="exportArrowUp" class="arrow-up" style="display: none;">▲</span>
                </button>
                <div id="exportDropdownMenu" class="dropdown-menu" style="display: none;">
                    <input type="radio" id="exportCsvOption" name="exportFormat" value="csv">
                    <label for="exportCsvOption"><?php echo htmlspecialchars(__('CSV'), ENT_QUOTES, 'UTF-8'); ?></label><br>
                    <input type="radio" id="exportXlsxOption" name="exportFormat" value="xls">
                    <label for="exportXlsxOption"><?php echo htmlspecialchars(__('Excel XML'), ENT_QUOTES, 'UTF-8'); ?></label><br>
                    <button id="cancelButton" style="font-size: 1rem; margin-top: 10px; background-color: #f1f1f1; padding: 5px 8px; margin-right: 10px;"><?php echo htmlspecialchars(__('Cancel'), ENT_QUOTES, 'UTF-8'); ?></button>
                    <button id="exportButton" style="font-size: 1rem; margin-top: 10px; background-color: #f1f1f1; padding: 5px 8px;"><?php echo htmlspecialchars(__('Export'), ENT_QUOTES, 'UTF-8'); ?></button>
                </div>
                </span>
                <!-- Export Button Implementation End -->
                <div class="paginationContainerTop" style="margin-left: auto; display: flex; align-items: center;">
                    <label for="rowsPerPage">Limit:</label>
                    <select id="rowsPerPage" style="margin: 0 0.5rem;">
                        <option value="5">5</option>
                        <option value="10">10</option>
                        <option value="15">15</option>
                        <option value="20" selected="">20</option>
                    </select>
                    <span id="paginationInfoTop" class="pagination-info">1 of 2</span>
                </div>
            </div>
        </div>

        <!-- Animated Filter Section -->
        <div id="filterSection">
			<?php if($allApprovalStatus): ?>
	            <div class="filter-item">
	                <label for="approvalStatus">Cause of failure:</label>
					<select id="approvalStatus">
							<option value="">Select</option>
						<?php foreach ($allApprovalStatus as $approvalStatus): ?>
							<option value="<?php echo  $approvalStatus; ?>"><?php echo  $approvalStatus; ?></option>
						<?php endforeach; ?>
					</select>
	            </div>
            <?php endif; ?>
            <?php if($allOrderState): ?>
	            <div class="filter-item">
	                <label for="orderState">Order State:</label>
					<select id="orderState">
							<option value="">Select</option>
						<?php foreach ($allOrderState as $orderState): ?>
							<option value="<?php echo  $orderState; ?>"><?php echo  $orderState; ?></option>
						<?php endforeach; ?>
					</select>
	            </div>
	        <?php endif; ?>
            <div class="filter-item">
                <label for="fromDate">From:</label>
                <input type="date" id="fromDate">
            </div>
            <div class="filter-item">
                <label for="toDate">To:</label>
                <input type="date" id="toDate">
            </div>
            <button id="resetFilter" style="font-size: 1rem; background-color: #f1f1f1; padding: 5px 15px;display: none;">RESET</button>
        </div>
    </div>

	<table id="transactionsTable" class="data-table">
		<thead>
			<tr>
				<th><?php echo __('Date/Time (UTC)'); ?></th>
				<th><?php echo __('Order ID'); ?></th>
				<th><?php echo __('Customer Name'); ?></th>
                <th><?php echo __('Order State'); ?>
                    <span class="tooltip-icon">&#9432;<span class="tooltip-text">
                            <strong>PROCESSING</strong>: This order is in a non-complete state. See "Cause of Failure".<br><br>
                            <strong>FAILED</strong>: This order has failed to complete. See "Cause of Failure".</span>
                    </span>
                </th>
				<th><?php echo __('Order Amount'); ?></th>
				<th><?php echo __('Cause of Failure'); ?></th>
				<th><?php echo __('IP Address'); ?></th>
				<th><?php echo __('Action'); ?></th>
			</tr>
		</thead>
		<tbody id="tableBody">
			<?php foreach ($orders as $order): ?>
				<tr>
					<td><?php echo isset($order['date_time']) ? $order['date_time'] : "N/A"; ?></td>
					<td><?php echo isset($order['order_increment_id']) ? $order['order_increment_id'] : "N/A"; ?></td>
					<td><?php echo isset($order['customer_name']) ? $order['customer_name'] : "N/A"; ?></td>
					<td><?php echo isset($order['order_state']) ? strtoupper($order['order_state']) : "N/A"; ?></td>
					<td><?php echo isset($order['grandTotal']) ? $order['grandTotal'] : "N/A"; ?></td>
					<td><?php echo isset($order['approval_status']) ? $order['approval_status'] : "N/A"; ?></td>
					<td><?php echo isset($order['remote_ip']) ? $order['remote_ip'] : "N/A"; ?></td>
					<td>
						<a href="<?php echo isset($order['orderViewUrl']) ? $order['orderViewUrl'] : "`"; ?>">View</a>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<div id="noRecordsMessage" style="display: none;margin-bottom: 20%;"><?php echo __('No failed orders found!'); ?></div>

	<div id="paginationControls" data-totalPage="<?php echo $totalPages; ?>"></div>
<?php else: ?>
	<div style="margin-bottom: 20%"><?php echo __('No failed orders found!'); ?></div>
<?php endif; ?>

<script type="text/x-magento-init">
{
	"*": {
		"Magento_Ui/js/core/app": {
			"components": {
				"failed-transaction": {
					"component": "Fiserv_Payments/js/view/declines/failed-transaction",
					"exportUrl" : "<?= $block->escapeUrl($block->getExportUrl()) ?>"
				}
			}
		}
	}
}
</script>
