<?php
	/** @var \Fiserv\Payments\Block\CommerceHub\Form $block */
	$code = $block->escapeHtml($block->getMethodCode());
?>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Fiserv_Payments/css/ch-form-admin.css')?>">

<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>"
		style="display:none">
	<div>

        	<div id="sdc-container">
                        <div class="sdc-row">
                                <div id="sdc-card-number-frame" class="sdc-field-frame sdc-text">
                                        <div id="sdc-card-brand-icon" class="sdc-card-brand-icon"></div>
                                        <div id="fiserv_commercehub-card-number" class="sdc-field"></div>
					<div
						id="sdc-unmask-number"
						class="sdc-unmasking-icon">
					</div>
					<div
						id="sdc-mask-number"
						class="sdc-masking-icon sdc-hidden">
					</div>
                                </div>
                                <span id="sdc-card-number-invalid-message" class="sdc-error-message sdc-hidden"></span>
                        </div>
                        <div class="sdc-row">
                                <div id="sdc-card-name-frame" class="sdc-field-frame sdc-text">
                                        <div id="fiserv_commercehub-name-on-card" class="sdc-field"></div>
					
                                </div>
                                <span id="sdc-card-name-invalid-message" class="sdc-error-message sdc-hidden"></span>
                        </div>
                        <div class="sdc-row">
                                <div id="sdc-security-code-frame" class="sdc-field-frame sdc-text">
                                        <div id="fiserv_commercehub-security-code" class="sdc-field"></div>
					<div
						id="sdc-unmask-security"
						class="sdc-unmasking-icon">
					</div>
					<div
						id="sdc-mask-security"
						class="sdc-masking-icon sdc-hidden">
					</div>
                                </div>
                                <span id="sdc-security-code-invalid-message" class="sdc-error-message sdc-hidden"></span>
                        </div>
                        <div class="sdc-column">
                                <div class="sdc-row">
                                        <div id="sdc-exp-month-frame" class="sdc-field-frame sdc-dropdown">
                                                <div id="fiserv_commercehub-expiration-month" class="sdc-field"></div>
                                        </div>
                                        <span id="sdc-exp-month-invalid-message" class="sdc-error-message sdc-hidden"></span>
                                </div>
                                <div class="sdc-row">
                                        <div id="sdc-exp-year-frame" class="sdc-field-frame sdc-dropdown">
                                                <div id="fiserv_commercehub-expiration-year" class="sdc-field"></div>
                                        </div>
                                        <span id="sdc-exp-year-invalid-message" class="sdc-error-message sdc-hidden"></span>
                                </div>
                        </div>
                </div>

		<input type="hidden" id="<?= /* @noEscape */ $code ?>_payment_session" name="payment[payment_session]"/>
	</div>
</fieldset>

<script type="application/javascript">
	if (jQuery('input#p_method_fiserv_commercehub').is(':checked')) 
	{	
		window.shouldInstantiateIframe = true;
		window.instantiateIframe();
	}
</script>
