<?php
	/** @var \Fiserv\Payments\Block\CommerceHub\AdminHtml\Order\Create\Billing\Method\Form $block */
	$scope = "fiserv-payments-admin-order-create";
?>

<div data-bind="scope: '<?= /* @noEscape */ $scope ?>'">
	<div>
		<input type="hidden" data-bind="afterRender: initPayment" />
	</div>
</div>


<script type="text/x-magento-init">
{
	"*": {
		"Magento_Ui/js/core/app": {
			"components": {
				"<?= /* @noEscape */ $scope ?>": {
					"component": "Fiserv_Payments/js/view/order/form/commercehub-form",
					"paymentConfig": <?= /* @escapeNotVerified */ $block->getConfig() ?>
				}
			}
		}
	}
}
</script>
