<?php

use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;

/** @var \Magento\Framework\View\Element\Template $block */
$details = $block->getData(TokenUiComponentProviderInterface::COMPONENT_DETAILS);
//$icon = $block->getData('icons')[$details['type']];
$id = $block->escapeHtml($block->getData('id'));
$code = $block->escapeHtml($block->getData('code'));
$expDelim = strpos($details['expirationDate'], '/');
$expMonth = substr($details['expirationDate'], 0, $expDelim);
$expYear = substr($details['expirationDate'], $expDelim + 1);
?>
<div data-mage-init='{
        "Fiserv_Payments/js/view/order/form/vault": {
            "container": "payment_<?= /* @noEscape */ $id ?>",
            "publicHash": "<?= $block->escapeHtml($block->getData(TokenUiComponentProviderInterface::COMPONENT_PUBLIC_HASH)) ?>",
            "code": "<?= $code ?>",
			"tokenUrl": "<?= $block->escapeUrl($block->getData('tokenUrl')) ?>"
        }
    }' id="payment_<?= /* @noEscape */ $id ?>" class="admin__field">
    <div class="admin__field-control control">
		<input type="hidden" id="<?= /* @noEscape */ $code ?>_token_source" name="payment[token_source]" value="<?= $details["tokenSource"] ?>" />
		<input type="hidden" id="<?= /* @noEscape */ $code ?>_expiration_month" name="payment[expiration_month]" value="<?= $expMonth ?>" />
        <input type="hidden" id="<?= /* @noEscape */ $code ?>_expiration_year" name="payment[expiration_year]" value="<?= $expYear ?>" />
		<input type="radio" id="token_switcher_<?= /* @noEscape */ $id ?>" name="payment[token_switcher]"/>
        <span><?= $block->escapeHtml(__('ending')) ?></span>
        <span><?= $block->escapeHtml(strtolower($details['maskedCC'])) ?></span>
        (<span><?= $block->escapeHtml(__('expires')) ?></span>:
        <span><?= $block->escapeHtml($details['expirationDate']) ?></span>)
    </div>
</div>

