<?php
/**
 * @var \Fiserv\Payments\Block\Valuelink\Adminhtml\Sales\CreditMemo\Totals $block
 */

$valuelinkCreditMemoTotal = $block->getValuelinkTotalForCreditMemo();
?>
<?php if ((float) $valuelinkCreditMemoTotal) : ?>
	<tr>
		<td class="label"><?= $block->escapeHtml(__('Gift Cards')) ?></td>
		<td>
			<span class="discount" style="white-space: nowrap;"><?= /* @noEscape */ $block->getOrder()->formatPrice(-$valuelinkCreditMemoTotal) ?></span>
		</td>
	</tr>
<?php endif; ?>
