<?php
/**
 * @var \Fiserv\Payments\Block\Adminhtml\Sales\Invoice\Totals $block
 */

$valuelinkInvoiceTotal = $block->getValuelinkTotalCapturedOnInvoice();
?>

<?php if ((float) $valuelinkInvoiceTotal) : ?>
	<tr>
		<td class="label"><?= $block->escapeHtml(__('Gift Cards')) ?></td>
		<td>
			<span class="discount" style="white-space: nowrap;"><?= /* @noEscape */ $block->getOrder()->formatPrice(-$valuelinkInvoiceTotal) ?></span>
		</td>
	</tr>
<?php endif; ?>
