<?php
/**
 * AdditionalPosInformation
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Hub
 *
 * This API Specification is designed to provide technical guidance required to consume and integrate with our APIs for payment processing.
 *
 * The version of the OpenAPI document: v1.24.08
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fiserv\Payments\Lib\CommerceHub\Model;

use \ArrayAccess;
use \Fiserv\Payments\Lib\CommerceHub\ObjectSerializer;

/**
 * AdditionalPosInformation Class Doc Comment
 *
 * @category Class
 * @description &lt;a href&#x3D;\&quot;../docs?path&#x3D;docs/Resources/Master-Data/Additional-POS-Info.md\&quot;&gt;Additional terminal&lt;/a&gt; or software specific information.
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AdditionalPosInformation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AdditionalPosInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'attended_terminal_data' => 'string',
        'alternate_routing_indicator' => 'bool',
        'cashback_limit' => 'float',
        'cardholder_activated_terminal_information' => 'string',
        'cashier_id' => 'string',
        'data_entry_source' => 'string',
        'host_discount_timestamp' => '\DateTime',
        'pos_card_table_version' => 'string',
        'pos_form_factor_indicator' => 'string',
        'pos_id' => 'string',
        'stan' => 'string',
        'supervisor_id' => 'string',
        'terminal_location' => 'string',
        'terminal_operator' => 'string',
        'transaction_qualifier' => 'string',
        'terminal_state_or_province' => 'string',
        'pos_hardware_and_software' => '\Fiserv\Payments\Lib\CommerceHub\Model\PosHardwareAndSoftware',
        'pos_features' => '\Fiserv\Payments\Lib\CommerceHub\Model\PosFeatures'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'attended_terminal_data' => null,
        'alternate_routing_indicator' => null,
        'cashback_limit' => null,
        'cardholder_activated_terminal_information' => null,
        'cashier_id' => null,
        'data_entry_source' => null,
        'host_discount_timestamp' => 'date-time',
        'pos_card_table_version' => null,
        'pos_form_factor_indicator' => null,
        'pos_id' => null,
        'stan' => null,
        'supervisor_id' => null,
        'terminal_location' => null,
        'terminal_operator' => null,
        'transaction_qualifier' => null,
        'terminal_state_or_province' => null,
        'pos_hardware_and_software' => null,
        'pos_features' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'attended_terminal_data' => false,
        'alternate_routing_indicator' => false,
        'cashback_limit' => false,
        'cardholder_activated_terminal_information' => false,
        'cashier_id' => false,
        'data_entry_source' => false,
        'host_discount_timestamp' => false,
        'pos_card_table_version' => false,
        'pos_form_factor_indicator' => false,
        'pos_id' => false,
        'stan' => false,
        'supervisor_id' => false,
        'terminal_location' => false,
        'terminal_operator' => false,
        'transaction_qualifier' => false,
        'terminal_state_or_province' => false,
        'pos_hardware_and_software' => false,
        'pos_features' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attended_terminal_data' => 'attendedTerminalData',
        'alternate_routing_indicator' => 'alternateRoutingIndicator',
        'cashback_limit' => 'cashbackLimit',
        'cardholder_activated_terminal_information' => 'cardholderActivatedTerminalInformation',
        'cashier_id' => 'cashierId',
        'data_entry_source' => 'dataEntrySource',
        'host_discount_timestamp' => 'hostDiscountTimestamp',
        'pos_card_table_version' => 'posCardTableVersion',
        'pos_form_factor_indicator' => 'posFormFactorIndicator',
        'pos_id' => 'posId',
        'stan' => 'stan',
        'supervisor_id' => 'supervisorId',
        'terminal_location' => 'terminalLocation',
        'terminal_operator' => 'terminalOperator',
        'transaction_qualifier' => 'transactionQualifier',
        'terminal_state_or_province' => 'terminalStateOrProvince',
        'pos_hardware_and_software' => 'posHardwareAndSoftware',
        'pos_features' => 'posFeatures'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attended_terminal_data' => 'setAttendedTerminalData',
        'alternate_routing_indicator' => 'setAlternateRoutingIndicator',
        'cashback_limit' => 'setCashbackLimit',
        'cardholder_activated_terminal_information' => 'setCardholderActivatedTerminalInformation',
        'cashier_id' => 'setCashierId',
        'data_entry_source' => 'setDataEntrySource',
        'host_discount_timestamp' => 'setHostDiscountTimestamp',
        'pos_card_table_version' => 'setPosCardTableVersion',
        'pos_form_factor_indicator' => 'setPosFormFactorIndicator',
        'pos_id' => 'setPosId',
        'stan' => 'setStan',
        'supervisor_id' => 'setSupervisorId',
        'terminal_location' => 'setTerminalLocation',
        'terminal_operator' => 'setTerminalOperator',
        'transaction_qualifier' => 'setTransactionQualifier',
        'terminal_state_or_province' => 'setTerminalStateOrProvince',
        'pos_hardware_and_software' => 'setPosHardwareAndSoftware',
        'pos_features' => 'setPosFeatures'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attended_terminal_data' => 'getAttendedTerminalData',
        'alternate_routing_indicator' => 'getAlternateRoutingIndicator',
        'cashback_limit' => 'getCashbackLimit',
        'cardholder_activated_terminal_information' => 'getCardholderActivatedTerminalInformation',
        'cashier_id' => 'getCashierId',
        'data_entry_source' => 'getDataEntrySource',
        'host_discount_timestamp' => 'getHostDiscountTimestamp',
        'pos_card_table_version' => 'getPosCardTableVersion',
        'pos_form_factor_indicator' => 'getPosFormFactorIndicator',
        'pos_id' => 'getPosId',
        'stan' => 'getStan',
        'supervisor_id' => 'getSupervisorId',
        'terminal_location' => 'getTerminalLocation',
        'terminal_operator' => 'getTerminalOperator',
        'transaction_qualifier' => 'getTransactionQualifier',
        'terminal_state_or_province' => 'getTerminalStateOrProvince',
        'pos_hardware_and_software' => 'getPosHardwareAndSoftware',
        'pos_features' => 'getPosFeatures'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('attended_terminal_data', $data ?? [], null);
        $this->setIfExists('alternate_routing_indicator', $data ?? [], null);
        $this->setIfExists('cashback_limit', $data ?? [], null);
        $this->setIfExists('cardholder_activated_terminal_information', $data ?? [], null);
        $this->setIfExists('cashier_id', $data ?? [], null);
        $this->setIfExists('data_entry_source', $data ?? [], null);
        $this->setIfExists('host_discount_timestamp', $data ?? [], null);
        $this->setIfExists('pos_card_table_version', $data ?? [], null);
        $this->setIfExists('pos_form_factor_indicator', $data ?? [], null);
        $this->setIfExists('pos_id', $data ?? [], null);
        $this->setIfExists('stan', $data ?? [], null);
        $this->setIfExists('supervisor_id', $data ?? [], null);
        $this->setIfExists('terminal_location', $data ?? [], null);
        $this->setIfExists('terminal_operator', $data ?? [], null);
        $this->setIfExists('transaction_qualifier', $data ?? [], null);
        $this->setIfExists('terminal_state_or_province', $data ?? [], null);
        $this->setIfExists('pos_hardware_and_software', $data ?? [], null);
        $this->setIfExists('pos_features', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['attended_terminal_data']) && (mb_strlen($this->container['attended_terminal_data']) > 16)) {
            $invalidProperties[] = "invalid value for 'attended_terminal_data', the character length must be smaller than or equal to 16.";
        }

        if (!is_null($this->container['cashback_limit']) && ($this->container['cashback_limit'] > 1.0E+18)) {
            $invalidProperties[] = "invalid value for 'cashback_limit', must be smaller than or equal to 1.0E+18.";
        }

        if (!is_null($this->container['cardholder_activated_terminal_information']) && (mb_strlen($this->container['cardholder_activated_terminal_information']) > 16)) {
            $invalidProperties[] = "invalid value for 'cardholder_activated_terminal_information', the character length must be smaller than or equal to 16.";
        }

        if (!is_null($this->container['data_entry_source']) && (mb_strlen($this->container['data_entry_source']) > 50)) {
            $invalidProperties[] = "invalid value for 'data_entry_source', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['pos_card_table_version']) && (mb_strlen($this->container['pos_card_table_version']) > 35)) {
            $invalidProperties[] = "invalid value for 'pos_card_table_version', the character length must be smaller than or equal to 35.";
        }

        if (!is_null($this->container['stan']) && (mb_strlen($this->container['stan']) > 6)) {
            $invalidProperties[] = "invalid value for 'stan', the character length must be smaller than or equal to 6.";
        }

        if (!is_null($this->container['terminal_location']) && (mb_strlen($this->container['terminal_location']) > 16)) {
            $invalidProperties[] = "invalid value for 'terminal_location', the character length must be smaller than or equal to 16.";
        }

        if (!is_null($this->container['terminal_operator']) && (mb_strlen($this->container['terminal_operator']) > 256)) {
            $invalidProperties[] = "invalid value for 'terminal_operator', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['terminal_state_or_province']) && (mb_strlen($this->container['terminal_state_or_province']) > 256)) {
            $invalidProperties[] = "invalid value for 'terminal_state_or_province', the character length must be smaller than or equal to 256.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attended_terminal_data
     *
     * @return string|null
     */
    public function getAttendedTerminalData()
    {
        return $this->container['attended_terminal_data'];
    }

    /**
     * Sets attended_terminal_data
     *
     * @param string|null $attended_terminal_data <a href=\"../docs?path=docs/Resources/Master-Data/Additional-POS-Info.md#attended-terminal-data>Attended terminal data</a> Indicates if the card acceptor was at the point of sale.
     *
     * @return self
     */
    public function setAttendedTerminalData($attended_terminal_data)
    {
        if (is_null($attended_terminal_data)) {
            throw new \InvalidArgumentException('non-nullable attended_terminal_data cannot be null');
        }
        if ((mb_strlen($attended_terminal_data) > 16)) {
            throw new \InvalidArgumentException('invalid length for $attended_terminal_data when calling AdditionalPosInformation., must be smaller than or equal to 16.');
        }

        $this->container['attended_terminal_data'] = $attended_terminal_data;

        return $this;
    }

    /**
     * Gets alternate_routing_indicator
     *
     * @return bool|null
     */
    public function getAlternateRoutingIndicator()
    {
        return $this->container['alternate_routing_indicator'];
    }

    /**
     * Sets alternate_routing_indicator
     *
     * @param bool|null $alternate_routing_indicator Identifies if the terminal support the Alternate Routing feature used for PINless POS, Signature Debit, and EMV Common AID features (excluding Online PIN CVM) allows merchants to process PIN Debit Network transactions without a PIN.
     *
     * @return self
     */
    public function setAlternateRoutingIndicator($alternate_routing_indicator)
    {
        if (is_null($alternate_routing_indicator)) {
            throw new \InvalidArgumentException('non-nullable alternate_routing_indicator cannot be null');
        }
        $this->container['alternate_routing_indicator'] = $alternate_routing_indicator;

        return $this;
    }

    /**
     * Gets cashback_limit
     *
     * @return float|null
     */
    public function getCashbackLimit()
    {
        return $this->container['cashback_limit'];
    }

    /**
     * Sets cashback_limit
     *
     * @param float|null $cashback_limit POS Cash back limit for the day.
     *
     * @return self
     */
    public function setCashbackLimit($cashback_limit)
    {
        if (is_null($cashback_limit)) {
            throw new \InvalidArgumentException('non-nullable cashback_limit cannot be null');
        }

        if (($cashback_limit > 1.0E+18)) {
            throw new \InvalidArgumentException('invalid value for $cashback_limit when calling AdditionalPosInformation., must be smaller than or equal to 1.0E+18.');
        }

        $this->container['cashback_limit'] = $cashback_limit;

        return $this;
    }

    /**
     * Gets cardholder_activated_terminal_information
     *
     * @return string|null
     */
    public function getCardholderActivatedTerminalInformation()
    {
        return $this->container['cardholder_activated_terminal_information'];
    }

    /**
     * Sets cardholder_activated_terminal_information
     *
     * @param string|null $cardholder_activated_terminal_information Identifies  <a href=\"../docs?path=docs/Resources/Master-Data/Additional-POS-Info.md#cardholder-activated-terminal-information> Cardholder Activated Terminal (CAT)</a> capabilities of the device.
     *
     * @return self
     */
    public function setCardholderActivatedTerminalInformation($cardholder_activated_terminal_information)
    {
        if (is_null($cardholder_activated_terminal_information)) {
            throw new \InvalidArgumentException('non-nullable cardholder_activated_terminal_information cannot be null');
        }
        if ((mb_strlen($cardholder_activated_terminal_information) > 16)) {
            throw new \InvalidArgumentException('invalid length for $cardholder_activated_terminal_information when calling AdditionalPosInformation., must be smaller than or equal to 16.');
        }

        $this->container['cardholder_activated_terminal_information'] = $cardholder_activated_terminal_information;

        return $this;
    }

    /**
     * Gets cashier_id
     *
     * @return string|null
     */
    public function getCashierId()
    {
        return $this->container['cashier_id'];
    }

    /**
     * Sets cashier_id
     *
     * @param string|null $cashier_id Used to uniquely identify the merchant's store cashier or employee accepting the transaction.
     *
     * @return self
     */
    public function setCashierId($cashier_id)
    {
        if (is_null($cashier_id)) {
            throw new \InvalidArgumentException('non-nullable cashier_id cannot be null');
        }
        $this->container['cashier_id'] = $cashier_id;

        return $this;
    }

    /**
     * Gets data_entry_source
     *
     * @return string|null
     */
    public function getDataEntrySource()
    {
        return $this->container['data_entry_source'];
    }

    /**
     * Sets data_entry_source
     *
     * @param string|null $data_entry_source ‘ <a href=\"../docs?path=docs/Resources/Master-Data/Additional-POS-Info.md&branch=main#data-entry-source”> Source </a> used to initiated transaction.’
     *
     * @return self
     */
    public function setDataEntrySource($data_entry_source)
    {
        if (is_null($data_entry_source)) {
            throw new \InvalidArgumentException('non-nullable data_entry_source cannot be null');
        }
        if ((mb_strlen($data_entry_source) > 50)) {
            throw new \InvalidArgumentException('invalid length for $data_entry_source when calling AdditionalPosInformation., must be smaller than or equal to 50.');
        }

        $this->container['data_entry_source'] = $data_entry_source;

        return $this;
    }

    /**
     * Gets host_discount_timestamp
     *
     * @return \DateTime|null
     */
    public function getHostDiscountTimestamp()
    {
        return $this->container['host_discount_timestamp'];
    }

    /**
     * Sets host_discount_timestamp
     *
     * @param \DateTime|null $host_discount_timestamp Identifies the timestamp used to support host discounts.
     *
     * @return self
     */
    public function setHostDiscountTimestamp($host_discount_timestamp)
    {
        if (is_null($host_discount_timestamp)) {
            throw new \InvalidArgumentException('non-nullable host_discount_timestamp cannot be null');
        }
        $this->container['host_discount_timestamp'] = $host_discount_timestamp;

        return $this;
    }

    /**
     * Gets pos_card_table_version
     *
     * @return string|null
     */
    public function getPosCardTableVersion()
    {
        return $this->container['pos_card_table_version'];
    }

    /**
     * Sets pos_card_table_version
     *
     * @param string|null $pos_card_table_version This field indicates the version of the card table  ID being downloaded.
     *
     * @return self
     */
    public function setPosCardTableVersion($pos_card_table_version)
    {
        if (is_null($pos_card_table_version)) {
            throw new \InvalidArgumentException('non-nullable pos_card_table_version cannot be null');
        }
        if ((mb_strlen($pos_card_table_version) > 35)) {
            throw new \InvalidArgumentException('invalid length for $pos_card_table_version when calling AdditionalPosInformation., must be smaller than or equal to 35.');
        }

        $this->container['pos_card_table_version'] = $pos_card_table_version;

        return $this;
    }

    /**
     * Gets pos_form_factor_indicator
     *
     * @return string|null
     */
    public function getPosFormFactorIndicator()
    {
        return $this->container['pos_form_factor_indicator'];
    }

    /**
     * Sets pos_form_factor_indicator
     *
     * @param string|null $pos_form_factor_indicator This field is used to identify the form factor used at the POS for MasterCard PayPass transactions. Note: Some values from 00–19 may indicate not only the physical form factor but also other attributes such as device technology and payment app specifications. Values from 20–99 exclusively indicate the form factor only without also indicating the storage technology.
     *
     * @return self
     */
    public function setPosFormFactorIndicator($pos_form_factor_indicator)
    {
        if (is_null($pos_form_factor_indicator)) {
            throw new \InvalidArgumentException('non-nullable pos_form_factor_indicator cannot be null');
        }
        $this->container['pos_form_factor_indicator'] = $pos_form_factor_indicator;

        return $this;
    }

    /**
     * Gets pos_id
     *
     * @return string|null
     */
    public function getPosId()
    {
        return $this->container['pos_id'];
    }

    /**
     * Sets pos_id
     *
     * @param string|null $pos_id Indicates the Point-of-Sale for multi-Controller Transactions.
     *
     * @return self
     */
    public function setPosId($pos_id)
    {
        if (is_null($pos_id)) {
            throw new \InvalidArgumentException('non-nullable pos_id cannot be null');
        }
        $this->container['pos_id'] = $pos_id;

        return $this;
    }

    /**
     * Gets stan
     *
     * @return string|null
     */
    public function getStan()
    {
        return $this->container['stan'];
    }

    /**
     * Sets stan
     *
     * @param string|null $stan System Trace or Debit Reg E Receipt Number - A system-generated number is provided by the merchant and it uniquely identifies a transaction. This number needs to be a unique number per Merchant and Terminal ID.
     *
     * @return self
     */
    public function setStan($stan)
    {
        if (is_null($stan)) {
            throw new \InvalidArgumentException('non-nullable stan cannot be null');
        }
        if ((mb_strlen($stan) > 6)) {
            throw new \InvalidArgumentException('invalid length for $stan when calling AdditionalPosInformation., must be smaller than or equal to 6.');
        }

        $this->container['stan'] = $stan;

        return $this;
    }

    /**
     * Gets supervisor_id
     *
     * @return string|null
     */
    public function getSupervisorId()
    {
        return $this->container['supervisor_id'];
    }

    /**
     * Sets supervisor_id
     *
     * @param string|null $supervisor_id Used to uniquely identify the merchant's store supervisor transactions.
     *
     * @return self
     */
    public function setSupervisorId($supervisor_id)
    {
        if (is_null($supervisor_id)) {
            throw new \InvalidArgumentException('non-nullable supervisor_id cannot be null');
        }
        $this->container['supervisor_id'] = $supervisor_id;

        return $this;
    }

    /**
     * Gets terminal_location
     *
     * @return string|null
     */
    public function getTerminalLocation()
    {
        return $this->container['terminal_location'];
    }

    /**
     * Sets terminal_location
     *
     * @param string|null $terminal_location Identifies the <a href=\"../docs?path=docs/Resources/Master-Data/Additional-POS-Info.md#location of the terminal></a> or software.
     *
     * @return self
     */
    public function setTerminalLocation($terminal_location)
    {
        if (is_null($terminal_location)) {
            throw new \InvalidArgumentException('non-nullable terminal_location cannot be null');
        }
        if ((mb_strlen($terminal_location) > 16)) {
            throw new \InvalidArgumentException('invalid length for $terminal_location when calling AdditionalPosInformation., must be smaller than or equal to 16.');
        }

        $this->container['terminal_location'] = $terminal_location;

        return $this;
    }

    /**
     * Gets terminal_operator
     *
     * @return string|null
     */
    public function getTerminalOperator()
    {
        return $this->container['terminal_operator'];
    }

    /**
     * Sets terminal_operator
     *
     * @param string|null $terminal_operator Person operating the terminal.  Valid Values: * MERCHANT * CUSTOMER * ADMINISTRATOR
     *
     * @return self
     */
    public function setTerminalOperator($terminal_operator)
    {
        if (is_null($terminal_operator)) {
            throw new \InvalidArgumentException('non-nullable terminal_operator cannot be null');
        }
        if ((mb_strlen($terminal_operator) > 256)) {
            throw new \InvalidArgumentException('invalid length for $terminal_operator when calling AdditionalPosInformation., must be smaller than or equal to 256.');
        }

        $this->container['terminal_operator'] = $terminal_operator;

        return $this;
    }

    /**
     * Gets transaction_qualifier
     *
     * @return string|null
     */
    public function getTransactionQualifier()
    {
        return $this->container['transaction_qualifier'];
    }

    /**
     * Sets transaction_qualifier
     *
     * @param string|null $transaction_qualifier Used for Discover - Discover TransactionQualifier.
     *
     * @return self
     */
    public function setTransactionQualifier($transaction_qualifier)
    {
        if (is_null($transaction_qualifier)) {
            throw new \InvalidArgumentException('non-nullable transaction_qualifier cannot be null');
        }
        $this->container['transaction_qualifier'] = $transaction_qualifier;

        return $this;
    }

    /**
     * Gets terminal_state_or_province
     *
     * @return string|null
     */
    public function getTerminalStateOrProvince()
    {
        return $this->container['terminal_state_or_province'];
    }

    /**
     * Sets terminal_state_or_province
     *
     * @param string|null $terminal_state_or_province POS location.
     *
     * @return self
     */
    public function setTerminalStateOrProvince($terminal_state_or_province)
    {
        if (is_null($terminal_state_or_province)) {
            throw new \InvalidArgumentException('non-nullable terminal_state_or_province cannot be null');
        }
        if ((mb_strlen($terminal_state_or_province) > 256)) {
            throw new \InvalidArgumentException('invalid length for $terminal_state_or_province when calling AdditionalPosInformation., must be smaller than or equal to 256.');
        }

        $this->container['terminal_state_or_province'] = $terminal_state_or_province;

        return $this;
    }

    /**
     * Gets pos_hardware_and_software
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\PosHardwareAndSoftware|null
     */
    public function getPosHardwareAndSoftware()
    {
        return $this->container['pos_hardware_and_software'];
    }

    /**
     * Sets pos_hardware_and_software
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\PosHardwareAndSoftware|null $pos_hardware_and_software pos_hardware_and_software
     *
     * @return self
     */
    public function setPosHardwareAndSoftware($pos_hardware_and_software)
    {
        if (is_null($pos_hardware_and_software)) {
            throw new \InvalidArgumentException('non-nullable pos_hardware_and_software cannot be null');
        }
        $this->container['pos_hardware_and_software'] = $pos_hardware_and_software;

        return $this;
    }

    /**
     * Gets pos_features
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\PosFeatures|null
     */
    public function getPosFeatures()
    {
        return $this->container['pos_features'];
    }

    /**
     * Sets pos_features
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\PosFeatures|null $pos_features pos_features
     *
     * @return self
     */
    public function setPosFeatures($pos_features)
    {
        if (is_null($pos_features)) {
            throw new \InvalidArgumentException('non-nullable pos_features cannot be null');
        }
        $this->container['pos_features'] = $pos_features;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


