<?php
/**
 * CancelResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payments
 *
 * This API Specification is designed to provide technical guidance required to consume and integrate with our APIs for payment processing.
 *
 * The version of the OpenAPI document: v1.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fiserv\Payments\Lib\CommerceHub\Model;

use \ArrayAccess;
use \Fiserv\Payments\Lib\CommerceHub\ObjectSerializer;

/**
 * CancelResponse Class Doc Comment
 *
 * @category Class
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CancelResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CancelResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'gateway_response' => '\Fiserv\Payments\Lib\CommerceHub\Model\GatewayResponse',
        'transaction_details' => '\Fiserv\Payments\Lib\CommerceHub\Model\TransactionDetails',
        'source' => '\Fiserv\Payments\Lib\CommerceHub\Model\Source',
        'merchant_details' => '\Fiserv\Payments\Lib\CommerceHub\Model\MerchantDetails',
        'payment_receipt' => '\Fiserv\Payments\Lib\CommerceHub\Model\PaymentReceipt',
        'transaction_batch' => '\Fiserv\Payments\Lib\CommerceHub\Model\TransactionBatch',
        'network_details' => '\Fiserv\Payments\Lib\CommerceHub\Model\NetworkDetails',
        'additional_data_common' => '\Fiserv\Payments\Lib\CommerceHub\Model\AdditionalDataCommon'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'gateway_response' => null,
        'transaction_details' => null,
        'source' => null,
        'merchant_details' => null,
        'payment_receipt' => null,
        'transaction_batch' => null,
        'network_details' => null,
        'additional_data_common' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'gateway_response' => false,
		'transaction_details' => false,
		'source' => false,
		'merchant_details' => false,
		'payment_receipt' => false,
		'transaction_batch' => false,
		'network_details' => false,
		'additional_data_common' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'gateway_response' => 'gatewayResponse',
        'transaction_details' => 'transactionDetails',
        'source' => 'source',
        'merchant_details' => 'merchantDetails',
        'payment_receipt' => 'paymentReceipt',
        'transaction_batch' => 'transactionBatch',
        'network_details' => 'networkDetails',
        'additional_data_common' => 'additionalDataCommon'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'gateway_response' => 'setGatewayResponse',
        'transaction_details' => 'setTransactionDetails',
        'source' => 'setSource',
        'merchant_details' => 'setMerchantDetails',
        'payment_receipt' => 'setPaymentReceipt',
        'transaction_batch' => 'setTransactionBatch',
        'network_details' => 'setNetworkDetails',
        'additional_data_common' => 'setAdditionalDataCommon'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'gateway_response' => 'getGatewayResponse',
        'transaction_details' => 'getTransactionDetails',
        'source' => 'getSource',
        'merchant_details' => 'getMerchantDetails',
        'payment_receipt' => 'getPaymentReceipt',
        'transaction_batch' => 'getTransactionBatch',
        'network_details' => 'getNetworkDetails',
        'additional_data_common' => 'getAdditionalDataCommon'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('gateway_response', $data ?? [], null);
        $this->setIfExists('transaction_details', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('merchant_details', $data ?? [], null);
        $this->setIfExists('payment_receipt', $data ?? [], null);
        $this->setIfExists('transaction_batch', $data ?? [], null);
        $this->setIfExists('network_details', $data ?? [], null);
        $this->setIfExists('additional_data_common', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets gateway_response
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\GatewayResponse|null
     */
    public function getGatewayResponse()
    {
        return $this->container['gateway_response'];
    }

    /**
     * Sets gateway_response
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\GatewayResponse|null $gateway_response gateway_response
     *
     * @return self
     */
    public function setGatewayResponse($gateway_response)
    {

        if (is_null($gateway_response)) {
            throw new \InvalidArgumentException('non-nullable gateway_response cannot be null');
        }

        $this->container['gateway_response'] = $gateway_response;

        return $this;
    }

    /**
     * Gets transaction_details
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\TransactionDetails|null
     */
    public function getTransactionDetails()
    {
        return $this->container['transaction_details'];
    }

    /**
     * Sets transaction_details
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\TransactionDetails|null $transaction_details transaction_details
     *
     * @return self
     */
    public function setTransactionDetails($transaction_details)
    {

        if (is_null($transaction_details)) {
            throw new \InvalidArgumentException('non-nullable transaction_details cannot be null');
        }

        $this->container['transaction_details'] = $transaction_details;

        return $this;
    }

    /**
     * Gets source
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\Source|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\Source|null $source source
     *
     * @return self
     */
    public function setSource($source)
    {

        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }

        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets merchant_details
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\MerchantDetails|null
     */
    public function getMerchantDetails()
    {
        return $this->container['merchant_details'];
    }

    /**
     * Sets merchant_details
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\MerchantDetails|null $merchant_details merchant_details
     *
     * @return self
     */
    public function setMerchantDetails($merchant_details)
    {

        if (is_null($merchant_details)) {
            throw new \InvalidArgumentException('non-nullable merchant_details cannot be null');
        }

        $this->container['merchant_details'] = $merchant_details;

        return $this;
    }

    /**
     * Gets payment_receipt
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\PaymentReceipt|null
     */
    public function getPaymentReceipt()
    {
        return $this->container['payment_receipt'];
    }

    /**
     * Sets payment_receipt
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\PaymentReceipt|null $payment_receipt payment_receipt
     *
     * @return self
     */
    public function setPaymentReceipt($payment_receipt)
    {

        if (is_null($payment_receipt)) {
            throw new \InvalidArgumentException('non-nullable payment_receipt cannot be null');
        }

        $this->container['payment_receipt'] = $payment_receipt;

        return $this;
    }

    /**
     * Gets transaction_batch
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\TransactionBatch|null
     */
    public function getTransactionBatch()
    {
        return $this->container['transaction_batch'];
    }

    /**
     * Sets transaction_batch
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\TransactionBatch|null $transaction_batch transaction_batch
     *
     * @return self
     */
    public function setTransactionBatch($transaction_batch)
    {

        if (is_null($transaction_batch)) {
            throw new \InvalidArgumentException('non-nullable transaction_batch cannot be null');
        }

        $this->container['transaction_batch'] = $transaction_batch;

        return $this;
    }

    /**
     * Gets network_details
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\NetworkDetails|null
     */
    public function getNetworkDetails()
    {
        return $this->container['network_details'];
    }

    /**
     * Sets network_details
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\NetworkDetails|null $network_details network_details
     *
     * @return self
     */
    public function setNetworkDetails($network_details)
    {

        if (is_null($network_details)) {
            throw new \InvalidArgumentException('non-nullable network_details cannot be null');
        }

        $this->container['network_details'] = $network_details;

        return $this;
    }

    /**
     * Gets additional_data_common
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\AdditionalDataCommon|null
     */
    public function getAdditionalDataCommon()
    {
        return $this->container['additional_data_common'];
    }

    /**
     * Sets additional_data_common
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\AdditionalDataCommon|null $additional_data_common additional_data_common
     *
     * @return self
     */
    public function setAdditionalDataCommon($additional_data_common)
    {

        if (is_null($additional_data_common)) {
            throw new \InvalidArgumentException('non-nullable additional_data_common cannot be null');
        }

        $this->container['additional_data_common'] = $additional_data_common;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


