<?php
/**
 * CheckoutInteractions
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Hub
 *
 * This API specification provides technical guidance for integrating with our payment processing APIs. Review the <a href=\"../docs?path=docs/Resources/API-Documents/OpenAPI-Specs.md\">Commerce Hub OpenAPI specification documentation</a> to learn about API versioning, deprecation policies, and to download the OpenAPI YAML definition.
 *
 * The version of the OpenAPI document: v1.25.2200
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fiserv\Payments\Lib\CommerceHub\Model;

use \ArrayAccess;
use \Fiserv\Payments\Lib\CommerceHub\ObjectSerializer;

/**
 * CheckoutInteractions Class Doc Comment
 *
 * @category Class
 * @description Customer interaction details for &lt;a href&#x3D;\&quot;../docs?path&#x3D;docs/Resources/API-Documents/Checkouts/Checkouts.md\&quot;&gt;checkout&lt;/a&gt;.
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CheckoutInteractions implements ModelInterface, ArrayAccess, \JsonSerializable
{
	public const DISCRIMINATOR = null;

	/**
	 * The original name of the model.
	 *
	 * @var string
	 */
	protected static $openAPIModelName = 'CheckoutInteractions';

	/**
	 * Array of property to type mappings. Used for (de)serialization
	 *
	 * @var string[]
	 */
	protected static $openAPITypes = [
		'channel' => 'string',
		'actions' => '\Fiserv\Payments\Lib\CommerceHub\Model\CheckoutInteractionsActions',
		'customer_confirmation' => 'string',
		'payment_initiator' => 'string',
		'return_urls' => '\Fiserv\Payments\Lib\CommerceHub\Model\CheckoutInteractionsReturnUrls'
	];

	/**
	 * Array of property to format mappings. Used for (de)serialization
	 *
	 * @var string[]
	 * @phpstan-var array<string, string|null>
	 * @psalm-var array<string, string|null>
	 */
	protected static $openAPIFormats = [
		'channel' => null,
		'actions' => null,
		'customer_confirmation' => null,
		'payment_initiator' => null,
		'return_urls' => null
	];

	/**
	 * Array of nullable properties. Used for (de)serialization
	 *
	 * @var boolean[]
	 */
	protected static array $openAPINullables = [
		'channel' => false,
		'actions' => false,
		'customer_confirmation' => false,
		'payment_initiator' => false,
		'return_urls' => false
	];

	/**
	 * If a nullable field gets set to null, insert it here
	 *
	 * @var boolean[]
	 */
	protected array $openAPINullablesSetToNull = [];

	/**
	 * Array of property to type mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function openAPITypes()
	{
		return self::$openAPITypes;
	}

	/**
	 * Array of property to format mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function openAPIFormats()
	{
		return self::$openAPIFormats;
	}

	/**
	 * Array of nullable properties
	 *
	 * @return array
	 */
	protected static function openAPINullables(): array
	{
		return self::$openAPINullables;
	}

	/**
	 * Array of nullable field names deliberately set to null
	 *
	 * @return boolean[]
	 */
	private function getOpenAPINullablesSetToNull(): array
	{
		return $this->openAPINullablesSetToNull;
	}

	/**
	 * Setter - Array of nullable field names deliberately set to null
	 *
	 * @param boolean[] $openAPINullablesSetToNull
	 */
	private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
	{
		$this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
	}

	/**
	 * Checks if a property is nullable
	 *
	 * @param string $property
	 * @return bool
	 */
	public static function isNullable(string $property): bool
	{
		return self::openAPINullables()[$property] ?? false;
	}

	/**
	 * Checks if a nullable property is set to null.
	 *
	 * @param string $property
	 * @return bool
	 */
	public function isNullableSetToNull(string $property): bool
	{
		return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
	}

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @var string[]
	 */
	protected static $attributeMap = [
		'channel' => 'channel',
		'actions' => 'actions',
		'customer_confirmation' => 'customerConfirmation',
		'payment_initiator' => 'paymentInitiator',
		'return_urls' => 'returnUrls'
	];

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @var string[]
	 */
	protected static $setters = [
		'channel' => 'setChannel',
		'actions' => 'setActions',
		'customer_confirmation' => 'setCustomerConfirmation',
		'payment_initiator' => 'setPaymentInitiator',
		'return_urls' => 'setReturnUrls'
	];

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @var string[]
	 */
	protected static $getters = [
		'channel' => 'getChannel',
		'actions' => 'getActions',
		'customer_confirmation' => 'getCustomerConfirmation',
		'payment_initiator' => 'getPaymentInitiator',
		'return_urls' => 'getReturnUrls'
	];

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @return array
	 */
	public static function attributeMap()
	{
		return self::$attributeMap;
	}

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @return array
	 */
	public static function setters()
	{
		return self::$setters;
	}

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @return array
	 */
	public static function getters()
	{
		return self::$getters;
	}

	/**
	 * The original name of the model.
	 *
	 * @return string
	 */
	public function getModelName()
	{
		return self::$openAPIModelName;
	}


	/**
	 * Associative array for storing property values
	 *
	 * @var mixed[]
	 */
	protected $container = [];

	/**
	 * Constructor
	 *
	 * @param mixed[] $data Associated array of property values
	 *                      initializing the model
	 */
	public function __construct(array $data = null)
	{
		$this->setIfExists('channel', $data ?? [], null);
		$this->setIfExists('actions', $data ?? [], null);
		$this->setIfExists('customer_confirmation', $data ?? [], null);
		$this->setIfExists('payment_initiator', $data ?? [], null);
		$this->setIfExists('return_urls', $data ?? [], null);
	}

	/**
	 * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
	 * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
	 * $this->openAPINullablesSetToNull array
	 *
	 * @param string $variableName
	 * @param array  $fields
	 * @param mixed  $defaultValue
	 */
	private function setIfExists(string $variableName, array $fields, $defaultValue): void
	{
		if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
			$this->openAPINullablesSetToNull[] = $variableName;
		}

		$this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
	}

	/**
	 * Show all the invalid properties with reasons.
	 *
	 * @return array invalid properties with reasons
	 */
	public function listInvalidProperties()
	{
		$invalidProperties = [];

		if (!is_null($this->container['channel']) && (mb_strlen($this->container['channel']) > 32)) {
			$invalidProperties[] = "invalid value for 'channel', the character length must be smaller than or equal to 32.";
		}

		if (!is_null($this->container['customer_confirmation']) && (mb_strlen($this->container['customer_confirmation']) > 32)) {
			$invalidProperties[] = "invalid value for 'customer_confirmation', the character length must be smaller than or equal to 32.";
		}

		if (!is_null($this->container['payment_initiator']) && (mb_strlen($this->container['payment_initiator']) > 32)) {
			$invalidProperties[] = "invalid value for 'payment_initiator', the character length must be smaller than or equal to 32.";
		}

		return $invalidProperties;
	}

	/**
	 * Validate all the properties in the model
	 * return true if all passed
	 *
	 * @return bool True if all properties are valid
	 */
	public function valid()
	{
		return count($this->listInvalidProperties()) === 0;
	}


	/**
	 * Gets channel
	 *
	 * @return string|null
	 */
	public function getChannel()
	{
		return $this->container['channel'];
	}

	/**
	 * Sets channel
	 *
	 * @param string|null $channel Type of interaction channel
	 *
	 * @return self
	 */
	public function setChannel($channel)
	{
		if (is_null($channel)) {
			throw new \InvalidArgumentException('non-nullable channel cannot be null');
		}
		if ((mb_strlen($channel) > 32)) {
			throw new \InvalidArgumentException('invalid length for $channel when calling CheckoutInteractions., must be smaller than or equal to 32.');
		}

		$this->container['channel'] = $channel;

		return $this;
	}

	/**
	 * Gets actions
	 *
	 * @return \Fiserv\Payments\Lib\CommerceHub\Model\CheckoutInteractionsActions|null
	 */
	public function getActions()
	{
		return $this->container['actions'];
	}

	/**
	 * Sets actions
	 *
	 * @param \Fiserv\Payments\Lib\CommerceHub\Model\CheckoutInteractionsActions|null $actions actions
	 *
	 * @return self
	 */
	public function setActions($actions)
	{
		if (is_null($actions)) {
			throw new \InvalidArgumentException('non-nullable actions cannot be null');
		}
		$this->container['actions'] = $actions;

		return $this;
	}

	/**
	 * Gets customer_confirmation
	 *
	 * @return string|null
	 */
	public function getCustomerConfirmation()
	{
		return $this->container['customer_confirmation'];
	}

	/**
	 * Sets customer_confirmation
	 *
	 * @param string|null $customer_confirmation Type of payment confirmation by customer. e.g.) PAY_NOW
	 *
	 * @return self
	 */
	public function setCustomerConfirmation($customer_confirmation)
	{
		if (is_null($customer_confirmation)) {
			throw new \InvalidArgumentException('non-nullable customer_confirmation cannot be null');
		}
		if ((mb_strlen($customer_confirmation) > 32)) {
			throw new \InvalidArgumentException('invalid length for $customer_confirmation when calling CheckoutInteractions., must be smaller than or equal to 32.');
		}

		$this->container['customer_confirmation'] = $customer_confirmation;

		return $this;
	}

	/**
	 * Gets payment_initiator
	 *
	 * @return string|null
	 */
	public function getPaymentInitiator()
	{
		return $this->container['payment_initiator'];
	}

	/**
	 * Sets payment_initiator
	 *
	 * @param string|null $payment_initiator Identify initiator of payment transaction. e.g.) GATEWAY
	 *
	 * @return self
	 */
	public function setPaymentInitiator($payment_initiator)
	{
		if (is_null($payment_initiator)) {
			throw new \InvalidArgumentException('non-nullable payment_initiator cannot be null');
		}
		if ((mb_strlen($payment_initiator) > 32)) {
			throw new \InvalidArgumentException('invalid length for $payment_initiator when calling CheckoutInteractions., must be smaller than or equal to 32.');
		}

		$this->container['payment_initiator'] = $payment_initiator;

		return $this;
	}

	/**
	 * Gets return_urls
	 *
	 * @return \Fiserv\Payments\Lib\CommerceHub\Model\CheckoutInteractionsReturnUrls|null
	 */
	public function getReturnUrls()
	{
		return $this->container['return_urls'];
	}

	/**
	 * Sets return_urls
	 *
	 * @param \Fiserv\Payments\Lib\CommerceHub\Model\CheckoutInteractionsReturnUrls|null $return_urls return_urls
	 *
	 * @return self
	 */
	public function setReturnUrls($return_urls)
	{
		if (is_null($return_urls)) {
			throw new \InvalidArgumentException('non-nullable return_urls cannot be null');
		}
		$this->container['return_urls'] = $return_urls;

		return $this;
	}
	/**
	 * Returns true if offset exists. False otherwise.
	 *
	 * @param integer $offset Offset
	 *
	 * @return boolean
	 */
	public function offsetExists($offset): bool
	{
		return isset($this->container[$offset]);
	}

	/**
	 * Gets offset.
	 *
	 * @param integer $offset Offset
	 *
	 * @return mixed|null
	 */
	#[\ReturnTypeWillChange]
	public function offsetGet($offset)
	{
		return $this->container[$offset] ?? null;
	}

	/**
	 * Sets value based on offset.
	 *
	 * @param int|null $offset Offset
	 * @param mixed    $value  Value to be set
	 *
	 * @return void
	 */
	public function offsetSet($offset, $value): void
	{
		if (is_null($offset)) {
			$this->container[] = $value;
		} else {
			$this->container[$offset] = $value;
		}
	}

	/**
	 * Unsets offset.
	 *
	 * @param integer $offset Offset
	 *
	 * @return void
	 */
	public function offsetUnset($offset): void
	{
		unset($this->container[$offset]);
	}

	/**
	 * Serializes the object to a value that can be serialized natively by json_encode().
	 * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
	 *
	 * @return mixed Returns data which can be serialized by json_encode(), which is a value
	 * of any type other than a resource.
	 */
	#[\ReturnTypeWillChange]
	public function jsonSerialize()
	{
		return ObjectSerializer::sanitizeForSerialization($this);
	}

	/**
	 * Gets the string presentation of the object
	 *
	 * @return string
	 */
	public function __toString()
	{
		return json_encode(
			ObjectSerializer::sanitizeForSerialization($this),
			JSON_PRETTY_PRINT
		);
	}

	/**
	 * Gets a header-safe presentation of the object
	 *
	 * @return string
	 */
	public function toHeaderValue()
	{
		return json_encode(ObjectSerializer::sanitizeForSerialization($this));
	}
}
