<?php
/**
 * GatewayResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payments
 *
 * This API Specification is designed to provide technical guidance required to consume and integrate with our APIs for payment processing.
 *
 * The version of the OpenAPI document: v1.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fiserv\Payments\Lib\CommerceHub\Model;

use \ArrayAccess;
use \Fiserv\Payments\Lib\CommerceHub\ObjectSerializer;

/**
 * GatewayResponse Class Doc Comment
 *
 * @category Class
 * @description Contains the &lt;a href&#x3D;\&quot;../docs?path&#x3D;docs/Resources/Master-Data/Gateway-Response.md\&quot;&gt;gateway response&lt;/a&gt; details.
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GatewayResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GatewayResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'transaction_type' => 'string',
        'transaction_state' => 'string',
        'transaction_origin' => 'string',
        'transaction_processing_details' => '\Fiserv\Payments\Lib\CommerceHub\Model\TransactionProcessingDetails'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'transaction_type' => null,
        'transaction_state' => null,
        'transaction_origin' => null,
        'transaction_processing_details' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'transaction_type' => false,
		'transaction_state' => false,
		'transaction_origin' => false,
		'transaction_processing_details' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transaction_type' => 'transactionType',
        'transaction_state' => 'transactionState',
        'transaction_origin' => 'transactionOrigin',
        'transaction_processing_details' => 'transactionProcessingDetails'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transaction_type' => 'setTransactionType',
        'transaction_state' => 'setTransactionState',
        'transaction_origin' => 'setTransactionOrigin',
        'transaction_processing_details' => 'setTransactionProcessingDetails'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transaction_type' => 'getTransactionType',
        'transaction_state' => 'getTransactionState',
        'transaction_origin' => 'getTransactionOrigin',
        'transaction_processing_details' => 'getTransactionProcessingDetails'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('transaction_type', $data ?? [], null);
        $this->setIfExists('transaction_state', $data ?? [], null);
        $this->setIfExists('transaction_origin', $data ?? [], null);
        $this->setIfExists('transaction_processing_details', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['transaction_type']) && (mb_strlen($this->container['transaction_type']) > 256)) {
            $invalidProperties[] = "invalid value for 'transaction_type', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['transaction_state']) && (mb_strlen($this->container['transaction_state']) > 256)) {
            $invalidProperties[] = "invalid value for 'transaction_state', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['transaction_origin']) && (mb_strlen($this->container['transaction_origin']) > 4)) {
            $invalidProperties[] = "invalid value for 'transaction_origin', the character length must be smaller than or equal to 4.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transaction_type
     *
     * @return string|null
     */
    public function getTransactionType()
    {
        return $this->container['transaction_type'];
    }

    /**
     * Sets transaction_type
     *
     * @param string|null $transaction_type Transaction type performed.
     *
     * @return self
     */
    public function setTransactionType($transaction_type)
    {
        if (!is_null($transaction_type) && (mb_strlen($transaction_type) > 256)) {
            throw new \InvalidArgumentException('invalid length for $transaction_type when calling GatewayResponse., must be smaller than or equal to 256.');
        }


        if (is_null($transaction_type)) {
            throw new \InvalidArgumentException('non-nullable transaction_type cannot be null');
        }

        $this->container['transaction_type'] = $transaction_type;

        return $this;
    }

    /**
     * Gets transaction_state
     *
     * @return string|null
     */
    public function getTransactionState()
    {
        return $this->container['transaction_state'];
    }

    /**
     * Sets transaction_state
     *
     * @param string|null $transaction_state Final state of the transaction.
     *
     * @return self
     */
    public function setTransactionState($transaction_state)
    {
        if (!is_null($transaction_state) && (mb_strlen($transaction_state) > 256)) {
            throw new \InvalidArgumentException('invalid length for $transaction_state when calling GatewayResponse., must be smaller than or equal to 256.');
        }


        if (is_null($transaction_state)) {
            throw new \InvalidArgumentException('non-nullable transaction_state cannot be null');
        }

        $this->container['transaction_state'] = $transaction_state;

        return $this;
    }

    /**
     * Gets transaction_origin
     *
     * @return string|null
     */
    public function getTransactionOrigin()
    {
        return $this->container['transaction_origin'];
    }

    /**
     * Sets transaction_origin
     *
     * @param string|null $transaction_origin Transaction origin based on original request.
     *
     * @return self
     */
    public function setTransactionOrigin($transaction_origin)
    {
        if (!is_null($transaction_origin) && (mb_strlen($transaction_origin) > 4)) {
            throw new \InvalidArgumentException('invalid length for $transaction_origin when calling GatewayResponse., must be smaller than or equal to 4.');
        }


        if (is_null($transaction_origin)) {
            throw new \InvalidArgumentException('non-nullable transaction_origin cannot be null');
        }

        $this->container['transaction_origin'] = $transaction_origin;

        return $this;
    }

    /**
     * Gets transaction_processing_details
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\TransactionProcessingDetails|null
     */
    public function getTransactionProcessingDetails()
    {
        return $this->container['transaction_processing_details'];
    }

    /**
     * Sets transaction_processing_details
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\TransactionProcessingDetails|null $transaction_processing_details transaction_processing_details
     *
     * @return self
     */
    public function setTransactionProcessingDetails($transaction_processing_details)
    {

        if (is_null($transaction_processing_details)) {
            throw new \InvalidArgumentException('non-nullable transaction_processing_details cannot be null');
        }

        $this->container['transaction_processing_details'] = $transaction_processing_details;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


