<?php
/**
 * PrivateLabel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Hub
 *
 * This API Specification is designed to provide technical guidance required to consume and integrate with our APIs for payment processing.
 *
 * The version of the OpenAPI document: v1.24.08
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fiserv\Payments\Lib\CommerceHub\Model;

use \ArrayAccess;
use \Fiserv\Payments\Lib\CommerceHub\ObjectSerializer;

/**
 * PrivateLabel Class Doc Comment
 *
 * @category Class
 * @description &lt;a href&#x3D;\&quot;../docs?path&#x3D;docs/Resources/Master-Data/Private-Label.md\&quot;&gt;Private label&lt;/a&gt; transaction information.
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PrivateLabel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PrivateLabel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'special_finance_indicator' => 'string',
        'credit_plan' => 'string',
        'minimum_spend_exempt_indicator' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'special_finance_indicator' => null,
        'credit_plan' => null,
        'minimum_spend_exempt_indicator' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'special_finance_indicator' => false,
        'credit_plan' => false,
        'minimum_spend_exempt_indicator' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'special_finance_indicator' => 'specialFinanceIndicator',
        'credit_plan' => 'creditPlan',
        'minimum_spend_exempt_indicator' => 'minimumSpendExemptIndicator'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'special_finance_indicator' => 'setSpecialFinanceIndicator',
        'credit_plan' => 'setCreditPlan',
        'minimum_spend_exempt_indicator' => 'setMinimumSpendExemptIndicator'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'special_finance_indicator' => 'getSpecialFinanceIndicator',
        'credit_plan' => 'getCreditPlan',
        'minimum_spend_exempt_indicator' => 'getMinimumSpendExemptIndicator'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('special_finance_indicator', $data ?? [], null);
        $this->setIfExists('credit_plan', $data ?? [], null);
        $this->setIfExists('minimum_spend_exempt_indicator', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['special_finance_indicator']) && (mb_strlen($this->container['special_finance_indicator']) > 16)) {
            $invalidProperties[] = "invalid value for 'special_finance_indicator', the character length must be smaller than or equal to 16.";
        }

        if (!is_null($this->container['credit_plan']) && (mb_strlen($this->container['credit_plan']) > 64)) {
            $invalidProperties[] = "invalid value for 'credit_plan', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['minimum_spend_exempt_indicator']) && (mb_strlen($this->container['minimum_spend_exempt_indicator']) > 32)) {
            $invalidProperties[] = "invalid value for 'minimum_spend_exempt_indicator', the character length must be smaller than or equal to 32.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets special_finance_indicator
     *
     * @return string|null
     */
    public function getSpecialFinanceIndicator()
    {
        return $this->container['special_finance_indicator'];
    }

    /**
     * Sets special_finance_indicator
     *
     * @param string|null $special_finance_indicator Indicates if special finance term and rate.
     *
     * @return self
     */
    public function setSpecialFinanceIndicator($special_finance_indicator)
    {
        if (is_null($special_finance_indicator)) {
            throw new \InvalidArgumentException('non-nullable special_finance_indicator cannot be null');
        }
        if ((mb_strlen($special_finance_indicator) > 16)) {
            throw new \InvalidArgumentException('invalid length for $special_finance_indicator when calling PrivateLabel., must be smaller than or equal to 16.');
        }

        $this->container['special_finance_indicator'] = $special_finance_indicator;

        return $this;
    }

    /**
     * Gets credit_plan
     *
     * @return string|null
     */
    public function getCreditPlan()
    {
        return $this->container['credit_plan'];
    }

    /**
     * Sets credit_plan
     *
     * @param string|null $credit_plan Payment program assigned by the private label processor.
     *
     * @return self
     */
    public function setCreditPlan($credit_plan)
    {
        if (is_null($credit_plan)) {
            throw new \InvalidArgumentException('non-nullable credit_plan cannot be null');
        }
        if ((mb_strlen($credit_plan) > 64)) {
            throw new \InvalidArgumentException('invalid length for $credit_plan when calling PrivateLabel., must be smaller than or equal to 64.');
        }

        $this->container['credit_plan'] = $credit_plan;

        return $this;
    }

    /**
     * Gets minimum_spend_exempt_indicator
     *
     * @return string|null
     */
    public function getMinimumSpendExemptIndicator()
    {
        return $this->container['minimum_spend_exempt_indicator'];
    }

    /**
     * Sets minimum_spend_exempt_indicator
     *
     * @param string|null $minimum_spend_exempt_indicator The minimum spend amount the customer is exempt from. Valid Values: * EXEMPT  * NOT_EXEMPT
     *
     * @return self
     */
    public function setMinimumSpendExemptIndicator($minimum_spend_exempt_indicator)
    {
        if (is_null($minimum_spend_exempt_indicator)) {
            throw new \InvalidArgumentException('non-nullable minimum_spend_exempt_indicator cannot be null');
        }
        if ((mb_strlen($minimum_spend_exempt_indicator) > 32)) {
            throw new \InvalidArgumentException('invalid length for $minimum_spend_exempt_indicator when calling PrivateLabel., must be smaller than or equal to 32.');
        }

        $this->container['minimum_spend_exempt_indicator'] = $minimum_spend_exempt_indicator;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


