<?php
/**
 * ReferenceTransactionDetails
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Hub
 *
 * This API Specification is designed to provide technical guidance required to consume and integrate with our APIs for payment processing.
 *
 * The version of the OpenAPI document: v1.24.08
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fiserv\Payments\Lib\CommerceHub\Model;

use \ArrayAccess;
use \Fiserv\Payments\Lib\CommerceHub\ObjectSerializer;

/**
 * ReferenceTransactionDetails Class Doc Comment
 *
 * @category Class
 * @description &lt;a href&#x3D;\&quot;../docs?path&#x3D;docs/Resources/Master-Data/Reference-Transaction-Details.md\&quot;&gt;Reference Transaction details&lt;/a&gt; specific to each request based on business requirements.
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ReferenceTransactionDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ReferenceTransactionDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'reference_transaction_id' => 'string',
        'reference_merchant_transaction_id' => 'string',
        'reference_merchant_order_id' => 'string',
        'reference_order_id' => 'string',
        'reference_client_request_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'reference_transaction_id' => null,
        'reference_merchant_transaction_id' => null,
        'reference_merchant_order_id' => null,
        'reference_order_id' => null,
        'reference_client_request_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'reference_transaction_id' => false,
        'reference_merchant_transaction_id' => false,
        'reference_merchant_order_id' => false,
        'reference_order_id' => false,
        'reference_client_request_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'reference_transaction_id' => 'referenceTransactionId',
        'reference_merchant_transaction_id' => 'referenceMerchantTransactionId',
        'reference_merchant_order_id' => 'referenceMerchantOrderId',
        'reference_order_id' => 'referenceOrderId',
        'reference_client_request_id' => 'referenceClientRequestId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'reference_transaction_id' => 'setReferenceTransactionId',
        'reference_merchant_transaction_id' => 'setReferenceMerchantTransactionId',
        'reference_merchant_order_id' => 'setReferenceMerchantOrderId',
        'reference_order_id' => 'setReferenceOrderId',
        'reference_client_request_id' => 'setReferenceClientRequestId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'reference_transaction_id' => 'getReferenceTransactionId',
        'reference_merchant_transaction_id' => 'getReferenceMerchantTransactionId',
        'reference_merchant_order_id' => 'getReferenceMerchantOrderId',
        'reference_order_id' => 'getReferenceOrderId',
        'reference_client_request_id' => 'getReferenceClientRequestId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('reference_transaction_id', $data ?? [], null);
        $this->setIfExists('reference_merchant_transaction_id', $data ?? [], null);
        $this->setIfExists('reference_merchant_order_id', $data ?? [], null);
        $this->setIfExists('reference_order_id', $data ?? [], null);
        $this->setIfExists('reference_client_request_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['reference_transaction_id']) && (mb_strlen($this->container['reference_transaction_id']) > 40)) {
            $invalidProperties[] = "invalid value for 'reference_transaction_id', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['reference_merchant_transaction_id']) && (mb_strlen($this->container['reference_merchant_transaction_id']) > 128)) {
            $invalidProperties[] = "invalid value for 'reference_merchant_transaction_id', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['reference_merchant_order_id']) && (mb_strlen($this->container['reference_merchant_order_id']) > 128)) {
            $invalidProperties[] = "invalid value for 'reference_merchant_order_id', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['reference_order_id']) && (mb_strlen($this->container['reference_order_id']) > 128)) {
            $invalidProperties[] = "invalid value for 'reference_order_id', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['reference_client_request_id']) && (mb_strlen($this->container['reference_client_request_id']) > 1024)) {
            $invalidProperties[] = "invalid value for 'reference_client_request_id', the character length must be smaller than or equal to 1024.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets reference_transaction_id
     *
     * @return string|null
     */
    public function getReferenceTransactionId()
    {
        return $this->container['reference_transaction_id'];
    }

    /**
     * Sets reference_transaction_id
     *
     * @param string|null $reference_transaction_id Commerce Hub generated <code>transactionId</code> from the original transaction used for reference in a secondary transaction.
     *
     * @return self
     */
    public function setReferenceTransactionId($reference_transaction_id)
    {
        if (is_null($reference_transaction_id)) {
            throw new \InvalidArgumentException('non-nullable reference_transaction_id cannot be null');
        }
        if ((mb_strlen($reference_transaction_id) > 40)) {
            throw new \InvalidArgumentException('invalid length for $reference_transaction_id when calling ReferenceTransactionDetails., must be smaller than or equal to 40.');
        }

        $this->container['reference_transaction_id'] = $reference_transaction_id;

        return $this;
    }

    /**
     * Gets reference_merchant_transaction_id
     *
     * @return string|null
     */
    public function getReferenceMerchantTransactionId()
    {
        return $this->container['reference_merchant_transaction_id'];
    }

    /**
     * Sets reference_merchant_transaction_id
     *
     * @param string|null $reference_merchant_transaction_id Merchant/client generated <code>merchantTransactionId</code> from the original transaction used for reference in a secondary transaction
     *
     * @return self
     */
    public function setReferenceMerchantTransactionId($reference_merchant_transaction_id)
    {
        if (is_null($reference_merchant_transaction_id)) {
            throw new \InvalidArgumentException('non-nullable reference_merchant_transaction_id cannot be null');
        }
        if ((mb_strlen($reference_merchant_transaction_id) > 128)) {
            throw new \InvalidArgumentException('invalid length for $reference_merchant_transaction_id when calling ReferenceTransactionDetails., must be smaller than or equal to 128.');
        }

        $this->container['reference_merchant_transaction_id'] = $reference_merchant_transaction_id;

        return $this;
    }

    /**
     * Gets reference_merchant_order_id
     *
     * @return string|null
     */
    public function getReferenceMerchantOrderId()
    {
        return $this->container['reference_merchant_order_id'];
    }

    /**
     * Sets reference_merchant_order_id
     *
     * @param string|null $reference_merchant_order_id Merchant/client generated <code>merchantOrderId</code> from the original transaction used for reference in a secondary transaction
     *
     * @return self
     */
    public function setReferenceMerchantOrderId($reference_merchant_order_id)
    {
        if (is_null($reference_merchant_order_id)) {
            throw new \InvalidArgumentException('non-nullable reference_merchant_order_id cannot be null');
        }
        if ((mb_strlen($reference_merchant_order_id) > 128)) {
            throw new \InvalidArgumentException('invalid length for $reference_merchant_order_id when calling ReferenceTransactionDetails., must be smaller than or equal to 128.');
        }

        $this->container['reference_merchant_order_id'] = $reference_merchant_order_id;

        return $this;
    }

    /**
     * Gets reference_order_id
     *
     * @return string|null
     */
    public function getReferenceOrderId()
    {
        return $this->container['reference_order_id'];
    }

    /**
     * Sets reference_order_id
     *
     * @param string|null $reference_order_id Commerce Hub generated <code>orderId</code> from the original transaction used for reference in a secondary transaction
     *
     * @return self
     */
    public function setReferenceOrderId($reference_order_id)
    {
        if (is_null($reference_order_id)) {
            throw new \InvalidArgumentException('non-nullable reference_order_id cannot be null');
        }
        if ((mb_strlen($reference_order_id) > 128)) {
            throw new \InvalidArgumentException('invalid length for $reference_order_id when calling ReferenceTransactionDetails., must be smaller than or equal to 128.');
        }

        $this->container['reference_order_id'] = $reference_order_id;

        return $this;
    }

    /**
     * Gets reference_client_request_id
     *
     * @return string|null
     */
    public function getReferenceClientRequestId()
    {
        return $this->container['reference_client_request_id'];
    }

    /**
     * Sets reference_client_request_id
     *
     * @param string|null $reference_client_request_id Merchant/client generated <code>clientRequestId</code> from the original transaction. Can only be used in a transaction inquiry request.
     *
     * @return self
     */
    public function setReferenceClientRequestId($reference_client_request_id)
    {
        if (is_null($reference_client_request_id)) {
            throw new \InvalidArgumentException('non-nullable reference_client_request_id cannot be null');
        }
        if ((mb_strlen($reference_client_request_id) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $reference_client_request_id when calling ReferenceTransactionDetails., must be smaller than or equal to 1024.');
        }

        $this->container['reference_client_request_id'] = $reference_client_request_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


