<?php
/**
 * RegionalDebit
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Hub
 *
 * This API Specification is designed to provide technical guidance required to consume and integrate with our APIs for payment processing.
 *
 * The version of the OpenAPI document: v1.24.08
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fiserv\Payments\Lib\CommerceHub\Model;

use \ArrayAccess;
use \Fiserv\Payments\Lib\CommerceHub\ObjectSerializer;

/**
 * RegionalDebit Class Doc Comment
 *
 * @category Class
 * @description Data that applies to &lt;a href&#x3D;\&quot;../docs?path&#x3D;docs/Resources/Guides/Debit/Regional-Debit.md\&quot;&gt;regional debit&lt;/a&gt; transactions.
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RegionalDebit implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RegionalDebit';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_type' => 'string',
        'debit_mac_value' => 'string',
        'mac_key_serial_number' => 'string',
        'mac_working_key' => 'string',
        'mac_working_key_check_digits' => 'string',
        'message_authentication_working_key' => 'string',
        'message_authentication_working_key_check_digits' => 'string',
        'message_encryption_working_key' => 'string',
        'pin_block' => '\Fiserv\Payments\Lib\CommerceHub\Model\PinBlock'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_type' => null,
        'debit_mac_value' => null,
        'mac_key_serial_number' => null,
        'mac_working_key' => null,
        'mac_working_key_check_digits' => null,
        'message_authentication_working_key' => null,
        'message_authentication_working_key_check_digits' => null,
        'message_encryption_working_key' => null,
        'pin_block' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'account_type' => false,
        'debit_mac_value' => false,
        'mac_key_serial_number' => false,
        'mac_working_key' => false,
        'mac_working_key_check_digits' => false,
        'message_authentication_working_key' => false,
        'message_authentication_working_key_check_digits' => false,
        'message_encryption_working_key' => false,
        'pin_block' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_type' => 'accountType',
        'debit_mac_value' => 'debitMacValue',
        'mac_key_serial_number' => 'macKeySerialNumber',
        'mac_working_key' => 'macWorkingKey',
        'mac_working_key_check_digits' => 'macWorkingKeyCheckDigits',
        'message_authentication_working_key' => 'messageAuthenticationWorkingKey',
        'message_authentication_working_key_check_digits' => 'messageAuthenticationWorkingKeyCheckDigits',
        'message_encryption_working_key' => 'messageEncryptionWorkingKey',
        'pin_block' => 'pinBlock'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_type' => 'setAccountType',
        'debit_mac_value' => 'setDebitMacValue',
        'mac_key_serial_number' => 'setMacKeySerialNumber',
        'mac_working_key' => 'setMacWorkingKey',
        'mac_working_key_check_digits' => 'setMacWorkingKeyCheckDigits',
        'message_authentication_working_key' => 'setMessageAuthenticationWorkingKey',
        'message_authentication_working_key_check_digits' => 'setMessageAuthenticationWorkingKeyCheckDigits',
        'message_encryption_working_key' => 'setMessageEncryptionWorkingKey',
        'pin_block' => 'setPinBlock'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_type' => 'getAccountType',
        'debit_mac_value' => 'getDebitMacValue',
        'mac_key_serial_number' => 'getMacKeySerialNumber',
        'mac_working_key' => 'getMacWorkingKey',
        'mac_working_key_check_digits' => 'getMacWorkingKeyCheckDigits',
        'message_authentication_working_key' => 'getMessageAuthenticationWorkingKey',
        'message_authentication_working_key_check_digits' => 'getMessageAuthenticationWorkingKeyCheckDigits',
        'message_encryption_working_key' => 'getMessageEncryptionWorkingKey',
        'pin_block' => 'getPinBlock'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('account_type', $data ?? [], null);
        $this->setIfExists('debit_mac_value', $data ?? [], null);
        $this->setIfExists('mac_key_serial_number', $data ?? [], null);
        $this->setIfExists('mac_working_key', $data ?? [], null);
        $this->setIfExists('mac_working_key_check_digits', $data ?? [], null);
        $this->setIfExists('message_authentication_working_key', $data ?? [], null);
        $this->setIfExists('message_authentication_working_key_check_digits', $data ?? [], null);
        $this->setIfExists('message_encryption_working_key', $data ?? [], null);
        $this->setIfExists('pin_block', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['mac_key_serial_number']) && (mb_strlen($this->container['mac_key_serial_number']) > 256)) {
            $invalidProperties[] = "invalid value for 'mac_key_serial_number', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['mac_working_key']) && (mb_strlen($this->container['mac_working_key']) > 16)) {
            $invalidProperties[] = "invalid value for 'mac_working_key', the character length must be smaller than or equal to 16.";
        }

        if (!is_null($this->container['mac_working_key_check_digits']) && (mb_strlen($this->container['mac_working_key_check_digits']) > 4)) {
            $invalidProperties[] = "invalid value for 'mac_working_key_check_digits', the character length must be smaller than or equal to 4.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_type
     *
     * @return string|null
     */
    public function getAccountType()
    {
        return $this->container['account_type'];
    }

    /**
     * Sets account_type
     *
     * @param string|null $account_type CHECKING or SAVINGS
     *
     * @return self
     */
    public function setAccountType($account_type)
    {
        if (is_null($account_type)) {
            throw new \InvalidArgumentException('non-nullable account_type cannot be null');
        }
        $this->container['account_type'] = $account_type;

        return $this;
    }

    /**
     * Gets debit_mac_value
     *
     * @return string|null
     */
    public function getDebitMacValue()
    {
        return $this->container['debit_mac_value'];
    }

    /**
     * Sets debit_mac_value
     *
     * @param string|null $debit_mac_value Used to confirm that the key data elements of the transaction have not been tampered.
     *
     * @return self
     */
    public function setDebitMacValue($debit_mac_value)
    {
        if (is_null($debit_mac_value)) {
            throw new \InvalidArgumentException('non-nullable debit_mac_value cannot be null');
        }
        $this->container['debit_mac_value'] = $debit_mac_value;

        return $this;
    }

    /**
     * Gets mac_key_serial_number
     *
     * @return string|null
     */
    public function getMacKeySerialNumber()
    {
        return $this->container['mac_key_serial_number'];
    }

    /**
     * Sets mac_key_serial_number
     *
     * @param string|null $mac_key_serial_number This field is used to create the base MAC encryption key for DUKPT PIN Debit, EBT, Fleet and Credit Transactions.
     *
     * @return self
     */
    public function setMacKeySerialNumber($mac_key_serial_number)
    {
        if (is_null($mac_key_serial_number)) {
            throw new \InvalidArgumentException('non-nullable mac_key_serial_number cannot be null');
        }
        if ((mb_strlen($mac_key_serial_number) > 256)) {
            throw new \InvalidArgumentException('invalid length for $mac_key_serial_number when calling RegionalDebit., must be smaller than or equal to 256.');
        }

        $this->container['mac_key_serial_number'] = $mac_key_serial_number;

        return $this;
    }

    /**
     * Gets mac_working_key
     *
     * @return string|null
     */
    public function getMacWorkingKey()
    {
        return $this->container['mac_working_key'];
    }

    /**
     * Sets mac_working_key
     *
     * @param string|null $mac_working_key A message authentication code for a working key that uses a session key to detect both accidental and intentional modifications of the data.
     *
     * @return self
     */
    public function setMacWorkingKey($mac_working_key)
    {
        if (is_null($mac_working_key)) {
            throw new \InvalidArgumentException('non-nullable mac_working_key cannot be null');
        }
        if ((mb_strlen($mac_working_key) > 16)) {
            throw new \InvalidArgumentException('invalid length for $mac_working_key when calling RegionalDebit., must be smaller than or equal to 16.');
        }

        $this->container['mac_working_key'] = $mac_working_key;

        return $this;
    }

    /**
     * Gets mac_working_key_check_digits
     *
     * @return string|null
     */
    public function getMacWorkingKeyCheckDigits()
    {
        return $this->container['mac_working_key_check_digits'];
    }

    /**
     * Sets mac_working_key_check_digits
     *
     * @param string|null $mac_working_key_check_digits A message authentication code for a working key that uses a session key to check digits.
     *
     * @return self
     */
    public function setMacWorkingKeyCheckDigits($mac_working_key_check_digits)
    {
        if (is_null($mac_working_key_check_digits)) {
            throw new \InvalidArgumentException('non-nullable mac_working_key_check_digits cannot be null');
        }
        if ((mb_strlen($mac_working_key_check_digits) > 4)) {
            throw new \InvalidArgumentException('invalid length for $mac_working_key_check_digits when calling RegionalDebit., must be smaller than or equal to 4.');
        }

        $this->container['mac_working_key_check_digits'] = $mac_working_key_check_digits;

        return $this;
    }

    /**
     * Gets message_authentication_working_key
     *
     * @return string|null
     */
    public function getMessageAuthenticationWorkingKey()
    {
        return $this->container['message_authentication_working_key'];
    }

    /**
     * Sets message_authentication_working_key
     *
     * @param string|null $message_authentication_working_key A message authentication code for a working key that uses a session key to detect both accidental and intentional modifications of the data.
     *
     * @return self
     */
    public function setMessageAuthenticationWorkingKey($message_authentication_working_key)
    {
        if (is_null($message_authentication_working_key)) {
            throw new \InvalidArgumentException('non-nullable message_authentication_working_key cannot be null');
        }
        $this->container['message_authentication_working_key'] = $message_authentication_working_key;

        return $this;
    }

    /**
     * Gets message_authentication_working_key_check_digits
     *
     * @return string|null
     */
    public function getMessageAuthenticationWorkingKeyCheckDigits()
    {
        return $this->container['message_authentication_working_key_check_digits'];
    }

    /**
     * Sets message_authentication_working_key_check_digits
     *
     * @param string|null $message_authentication_working_key_check_digits A message authentication code for a working key that uses a session key to check digits.
     *
     * @return self
     */
    public function setMessageAuthenticationWorkingKeyCheckDigits($message_authentication_working_key_check_digits)
    {
        if (is_null($message_authentication_working_key_check_digits)) {
            throw new \InvalidArgumentException('non-nullable message_authentication_working_key_check_digits cannot be null');
        }
        $this->container['message_authentication_working_key_check_digits'] = $message_authentication_working_key_check_digits;

        return $this;
    }

    /**
     * Gets message_encryption_working_key
     *
     * @return string|null
     */
    public function getMessageEncryptionWorkingKey()
    {
        return $this->container['message_encryption_working_key'];
    }

    /**
     * Sets message_encryption_working_key
     *
     * @param string|null $message_encryption_working_key A message encryption working key is typically a random string of bits generated specifically to scramble and unscramble data.
     *
     * @return self
     */
    public function setMessageEncryptionWorkingKey($message_encryption_working_key)
    {
        if (is_null($message_encryption_working_key)) {
            throw new \InvalidArgumentException('non-nullable message_encryption_working_key cannot be null');
        }
        $this->container['message_encryption_working_key'] = $message_encryption_working_key;

        return $this;
    }

    /**
     * Gets pin_block
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\PinBlock|null
     */
    public function getPinBlock()
    {
        return $this->container['pin_block'];
    }

    /**
     * Sets pin_block
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\PinBlock|null $pin_block pin_block
     *
     * @return self
     */
    public function setPinBlock($pin_block)
    {
        if (is_null($pin_block)) {
            throw new \InvalidArgumentException('non-nullable pin_block cannot be null');
        }
        $this->container['pin_block'] = $pin_block;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


