<?php
/**
 * TokenizationRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Hub
 *
 * This API Specification is designed to provide technical guidance required to consume and integrate with our APIs for payment processing.
 *
 * The version of the OpenAPI document: v1.24.08
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fiserv\Payments\Lib\CommerceHub\Model;

use \ArrayAccess;
use \Fiserv\Payments\Lib\CommerceHub\ObjectSerializer;

/**
 * TokenizationRequest Class Doc Comment
 *
 * @category Class
 * @package  Fiserv\Payments\Lib\CommerceHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TokenizationRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TokenizationRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'source' => '\Fiserv\Payments\Lib\CommerceHub\Model\Source',
        'transaction_details' => '\Fiserv\Payments\Lib\CommerceHub\Model\TransactionDetails',
        'additional_data_common' => '\Fiserv\Payments\Lib\CommerceHub\Model\AdditionalDataCommon',
        'merchant_details' => '\Fiserv\Payments\Lib\CommerceHub\Model\MerchantDetails',
        'billing_address' => '\Fiserv\Payments\Lib\CommerceHub\Model\BillingAddress',
        'transaction_interaction' => '\Fiserv\Payments\Lib\CommerceHub\Model\TransactionInteraction',
        'additional_data3_ds' => '\Fiserv\Payments\Lib\CommerceHub\Model\AdditionalData3DS',
        'stored_credentials' => '\Fiserv\Payments\Lib\CommerceHub\Model\StoredCredentials'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'source' => null,
        'transaction_details' => null,
        'additional_data_common' => null,
        'merchant_details' => null,
        'billing_address' => null,
        'transaction_interaction' => null,
        'additional_data3_ds' => null,
        'stored_credentials' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'source' => false,
        'transaction_details' => false,
        'additional_data_common' => false,
        'merchant_details' => false,
        'billing_address' => false,
        'transaction_interaction' => false,
        'additional_data3_ds' => false,
        'stored_credentials' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'source' => 'source',
        'transaction_details' => 'transactionDetails',
        'additional_data_common' => 'additionalDataCommon',
        'merchant_details' => 'merchantDetails',
        'billing_address' => 'billingAddress',
        'transaction_interaction' => 'transactionInteraction',
        'additional_data3_ds' => 'additionalData3DS',
        'stored_credentials' => 'storedCredentials'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'source' => 'setSource',
        'transaction_details' => 'setTransactionDetails',
        'additional_data_common' => 'setAdditionalDataCommon',
        'merchant_details' => 'setMerchantDetails',
        'billing_address' => 'setBillingAddress',
        'transaction_interaction' => 'setTransactionInteraction',
        'additional_data3_ds' => 'setAdditionalData3Ds',
        'stored_credentials' => 'setStoredCredentials'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'source' => 'getSource',
        'transaction_details' => 'getTransactionDetails',
        'additional_data_common' => 'getAdditionalDataCommon',
        'merchant_details' => 'getMerchantDetails',
        'billing_address' => 'getBillingAddress',
        'transaction_interaction' => 'getTransactionInteraction',
        'additional_data3_ds' => 'getAdditionalData3Ds',
        'stored_credentials' => 'getStoredCredentials'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('transaction_details', $data ?? [], null);
        $this->setIfExists('additional_data_common', $data ?? [], null);
        $this->setIfExists('merchant_details', $data ?? [], null);
        $this->setIfExists('billing_address', $data ?? [], null);
        $this->setIfExists('transaction_interaction', $data ?? [], null);
        $this->setIfExists('additional_data3_ds', $data ?? [], null);
        $this->setIfExists('stored_credentials', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets source
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\Source|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\Source|null $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets transaction_details
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\TransactionDetails|null
     */
    public function getTransactionDetails()
    {
        return $this->container['transaction_details'];
    }

    /**
     * Sets transaction_details
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\TransactionDetails|null $transaction_details transaction_details
     *
     * @return self
     */
    public function setTransactionDetails($transaction_details)
    {
        if (is_null($transaction_details)) {
            throw new \InvalidArgumentException('non-nullable transaction_details cannot be null');
        }
        $this->container['transaction_details'] = $transaction_details;

        return $this;
    }

    /**
     * Gets additional_data_common
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\AdditionalDataCommon|null
     */
    public function getAdditionalDataCommon()
    {
        return $this->container['additional_data_common'];
    }

    /**
     * Sets additional_data_common
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\AdditionalDataCommon|null $additional_data_common additional_data_common
     *
     * @return self
     */
    public function setAdditionalDataCommon($additional_data_common)
    {
        if (is_null($additional_data_common)) {
            throw new \InvalidArgumentException('non-nullable additional_data_common cannot be null');
        }
        $this->container['additional_data_common'] = $additional_data_common;

        return $this;
    }

    /**
     * Gets merchant_details
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\MerchantDetails|null
     */
    public function getMerchantDetails()
    {
        return $this->container['merchant_details'];
    }

    /**
     * Sets merchant_details
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\MerchantDetails|null $merchant_details merchant_details
     *
     * @return self
     */
    public function setMerchantDetails($merchant_details)
    {
        if (is_null($merchant_details)) {
            throw new \InvalidArgumentException('non-nullable merchant_details cannot be null');
        }
        $this->container['merchant_details'] = $merchant_details;

        return $this;
    }

    /**
     * Gets billing_address
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\BillingAddress|null
     */
    public function getBillingAddress()
    {
        return $this->container['billing_address'];
    }

    /**
     * Sets billing_address
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\BillingAddress|null $billing_address billing_address
     *
     * @return self
     */
    public function setBillingAddress($billing_address)
    {
        if (is_null($billing_address)) {
            throw new \InvalidArgumentException('non-nullable billing_address cannot be null');
        }
        $this->container['billing_address'] = $billing_address;

        return $this;
    }

    /**
     * Gets transaction_interaction
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\TransactionInteraction|null
     */
    public function getTransactionInteraction()
    {
        return $this->container['transaction_interaction'];
    }

    /**
     * Sets transaction_interaction
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\TransactionInteraction|null $transaction_interaction transaction_interaction
     *
     * @return self
     */
    public function setTransactionInteraction($transaction_interaction)
    {
        if (is_null($transaction_interaction)) {
            throw new \InvalidArgumentException('non-nullable transaction_interaction cannot be null');
        }
        $this->container['transaction_interaction'] = $transaction_interaction;

        return $this;
    }

    /**
     * Gets additional_data3_ds
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\AdditionalData3DS|null
     */
    public function getAdditionalData3Ds()
    {
        return $this->container['additional_data3_ds'];
    }

    /**
     * Sets additional_data3_ds
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\AdditionalData3DS|null $additional_data3_ds additional_data3_ds
     *
     * @return self
     */
    public function setAdditionalData3Ds($additional_data3_ds)
    {
        if (is_null($additional_data3_ds)) {
            throw new \InvalidArgumentException('non-nullable additional_data3_ds cannot be null');
        }
        $this->container['additional_data3_ds'] = $additional_data3_ds;

        return $this;
    }

    /**
     * Gets stored_credentials
     *
     * @return \Fiserv\Payments\Lib\CommerceHub\Model\StoredCredentials|null
     */
    public function getStoredCredentials()
    {
        return $this->container['stored_credentials'];
    }

    /**
     * Sets stored_credentials
     *
     * @param \Fiserv\Payments\Lib\CommerceHub\Model\StoredCredentials|null $stored_credentials stored_credentials
     *
     * @return self
     */
    public function setStoredCredentials($stored_credentials)
    {
        if (is_null($stored_credentials)) {
            throw new \InvalidArgumentException('non-nullable stored_credentials cannot be null');
        }
        $this->container['stored_credentials'] = $stored_credentials;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


