<?php

namespace Fiserv\Payments\view\frontend\templates\cart\valuelink;

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Fiserv\Payments\Block\Checkout\Valuelink\Cart\Total;

/*
 * @var Total $block
 * @var SecureHtmlRenderer $secureRenderer
 * @var Escaper $escaper
 */

<tr class="totals valuelink">
	<th colspan="<?= $escaper->escapeHtmlAttr($block->getColspan()) ?>"
		<span>HELLO HI HELLO</span>
	</th>	
</tr>
